### ISSUE TITLE
 In the Taghmata List, there is only Ordo Reductor as Legio selectable. Just add Legio, and try to select

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1054]
**File:** (HH) Mechanicum - Taghmata Army List.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** In the Taghmata List, there is only Ordo Reductor as Legio selectable. Just add Legio, and try to select

**Comment by capitaladot** [comment]
Hey @zopha, any idea what happened here? 

I see hides on the other two Legios except if Matrix of Ruin... that makes no sense.
Also, Legio should be a required selection with a default of Taghmata Omnissiah. That's the default list.

Reductor and Cybernetica engage a bunch of show/hides of copies of Troops (as they have different rules on what is compulsory vs. optional).
Matrix of Ruin is an alternative FoC that Ordo Reductor can take, but is not required to.

Cybernetica is an alternative list that has some unique HQ choices, etc, so selecting Cybernetica should therefor be required to make those legal selections. Whether they're hidden or not is more debatable. I am kind of in favor of not hiding them to reduce confusion.
Show all options, and if someone picks one that is illegal, inform them of the missing thing that makes their selection illegal via a validation error, rather than making people guess the formula to reveal the thing they want to add.
