### ISSUE TITLE
FoTA Dreadnought Issues

### ISSUE THREAD

**Issue by alphalas** [BSData/horus-heresy#1064]
- [x] Neither Contemptor or Legion Dreadnoughts are fulfilling the min2 compulsory Walker constraint.
- [x] Legion Dreadnoughts have a Max2 that will incorrectly disallow Extra Armour, Frag Assault Launchers, and Armoured Ceramite.

**Comment by capitaladot** [comment]
Do they have the Walker Category on the Unit links?

On Aug 1, 2017 7:45 PM, "Jon Kissinger" <notifications@github.com> wrote:


   - Neither Contemptor or Legion Dreadnoughts are fulfilling the min2
   compulsory Walker constraint.
   - Legion Dreadnoughts have a Max2 that will incorrectly disallow Extra
   Armour, Frag Assault Launchers, and Armoured Ceramite.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/1064>, or mute the thread

**Comment by capitaladot** [comment]
Likewise, the Troops links will need the Compulsory Troops Category.
