### ISSUE TITLE
IPhone 6 Legions Astartes crash bug

### ISSUE THREAD

**Issue by kraytirous** [BSData/horus-heresy#1099]
I'm using battlescribe version 2.01.05 and Horus Heresy 9.0.5 on my iPhone 6. Every time I open a Legions Astartes roster of any sort, there's a long load time and the app crashes both on new rosters and existing rosters. I saw the advice to install Java in 64 bit and it fixed the similar bug on my pc, but isn't an option on iPhone. To be clear, every other type of army (Talons of the Emperor, mechanicum, etc) work just fine until I try to add a roster of LA. Then the app crashes.

**Comment by alphalas** [comment]
What version of iOS are you running? My 7 has no issues

**Comment by alphalas** [comment]
Also your HH GST ver number should be at least v87, AoDAL ver number should be at least v479

**Comment by kraytirous** [comment]
I'm running iOS 10.3.3. It is Horus Heresy v87 and AoDAL is v479 exactly.

**Comment by alphalas** [comment]
That's weird - must be something hardware related then because I too am running 10.3.3, bs 2.01.05 on my iPhone 7

**Comment by kraytirous** [comment]
Any advice on how to troubleshoot it?

**Comment by alphalas** [comment]
How much available space do you have on your phone?

**Comment by kraytirous** [comment]
2.66 GB

**Comment by capitaladot** [comment]
Do you have tons of other apps open while trying to run it? You might force-close a few before trying and seeing if you get different behavior.
Another thing you might try is with or without Dropbox.
BS2 seems to have some memory usage problems across platforms.

**Comment by kraytirous** [comment]
Hi capitaladot,

I've turned off every other app except for battlescribe through forceclose, tried it both with and without Dropbox. It still isn't allowing me to make new rosters.

**Comment by capitaladot** [comment]
Bummer. We are discussing some changes to improve performance. It is tough
to tell what the exact issue is, but there are a few ideas we think could
help.

On Sep 5, 2017 5:23 PM, "kraytirous" <notifications@github.com> wrote:

Hi capitaladot,

I've turned off every other app except for battlescribe through forceclose,
tried it both with and without Dropbox. It still isn't allowing me to make
new rosters.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/1099#issuecomment-327307624>,
or mute the thread

**Comment by kraytirous** [comment]
Please let me know if there's anything I can do to help, or more information I can give that'll help.

**Comment by alphalas** [comment]
hey @kraytirous, join us on gitter - i have a couple other troubleshooting things i'd like for you to try
https://gitter.im/BSData/horus-heresy
