### ISSUE TITLE
ImperialMilitia & Cults LoW missing

### ISSUE THREAD

**Issue by akujiro** [BSData/horus-heresy#1102]
Additional LoW missing (Shadowsword, Stormlord etc.)as per legions red book page 10
using additional super-heavy and orbital strike wing units. As per written this units can be used  to any HH army,  legions lis only takes advantage using space marine crew option

**Comment by capitaladot** [comment]
Please cite the passage stating that the section in Age of Darkness Army List replaces the passage in Crusade Army List.

**Comment by akujiro** [comment]
«The vast milieu of battle during the Horus Heresy and the armies of the Great Crusade were staggeringly diverse, with only the most common or singular currently dealt with by Forge World’s Horus Heresy supplements. In order to represent this diversity when it comes to Super-heavy vehicles an»

Отрывок из книги: Forgeworld (Gamesworkshop Ltd). «The Horus Heresy

**Comment by akujiro** [comment]
«The vast milieu of battle during the Horus Heresy and the armies of the Great Crusade were staggeringly diverse, with only the most common or singular currently dealt with by Forge World’s Horus Heresy supplements. In order to represent this diversity when it comes to Super-heavy vehicles and Flyers, this section presents a list of additional models which may be used»

**Comment by capitaladot** [comment]
That says nothing suggesting that the rules passage from AoDAL
replaces those in the other book.

**Comment by akujiro** [comment]
It's from last legions army list , I think it's bisicly says that's you can use listed models in addition to those listed in  in any Age of darkness army list. As it's already implemented  in legions.

**Comment by capitaladot** [comment]
It doesn't say that it applies to any other army list.

**Comment by akujiro** [comment]
Well not directly but  it's under battles age of darkness section and passage says abaut armies of the great crusade not only legions

**Comment by akujiro** [comment]
I have contacted forge world to clarify this and they answered : 
"Thanks for contacting us and that rule applies to all Horus Heresy armies"

**Comment by TomTheHand** [comment]
I've been unclear about whether this rule applies to armies other than Space Marine Legions, though it does make sense. Note, however, that this rule does not apply to "Shadowsword, Stormlord etc."; it only applies to vehicles that do not currently have rules in 30k (like the Crassus transport or Marauder bomber).

**Comment by akujiro** [comment]
Whay not? Rule saying that  all vehicles from the list can be used. It just says if there no rules for than in hh books use rules from ia etc

**Comment by capitaladot** [comment]
@TomTheHand: huh?

Using additional Super-heavy & Orbital Strike Wing Flyer Units
The vast milieu of battle during the Horus Heresy and the armies of the
Great Crusade were staggeringly diverse, with only the most common or
singular currently dealt with by Forge World’s Horus Heresy supplements. In
order to represent this diversity when it comes to Super-heavy vehicles and
Flyers, this section presents a list of additional models which may be
used. In many cases, the Imperium of the Great Crusade sees the origin of
some of these designs, while in others they can simply be used to stand in
for one of the many less-widespread war machine types and unique patterns
employed by a vast Imperial armed force, far less regimented and
standardised than its 41st Millennium counterpart. Where general options
are listed but not found on the vehicle’s profile or within this book, or
refer explicitly to the 41st Millennium (i.e., Commissar tanks), ignore
those options:
Baneblade, Banehammer, Stormlord, Shadowsword, Stormsword
Macharius and variants (representing indigenous war machines)
Crassus and variants (representing indigenous war machines)
Marauder Bomber, Marauder Destroyer, Thunderbolt Heavy Fighter, Crusade
Avenger Strike Fighter (see Mechanicum Taghmata army list)
Minotaur (see Taghmata Omnissiah army list)
When used in conjunction with this army list, these vehicles may be further
modified by the following upgrades:
Space Marine Crew (Super-heavy Tanks only): +15 points
Battle Servitor Control (Flyers only): +15 points. If taken as an option
for a Sub-orbital Strike Wing, then all the Flyers in the wing must be so
upgraded.

**Comment by akujiro** [comment]
Yep that's one

**Comment by akujiro** [comment]
it's logical to use those vichicles for for example militia list

**Comment by TomTheHand** [comment]
@capitaladot

Whoops! My bad. I wasn't looking at the Age of Darkness Army List; I was remembering older lists.

The Legiones Astartes Crusade Army List (which has been superceded by AoDAL) and Mechanicum Taghmata Army List say that Legions and Mechanicum can take any Forge World Imperial Super-Heavies that don't have 30k versions as Lords of War, and each book presents some faction-specific upgrades that can be applied to those Super-Heavies.

The Legiones Astartes Age of Darkness Army List presents a specific list of Super-Heavies that aren't included in the book, but that are able to be taken as Lords of War.

The Crusade Imperialis Army Lists specifies exactly what Lords of War the Solar Auxilia and Questoris Knight Crusade Army can take. Specifically, the Auxilia get the LoW included in their section of the book, plus Knights from the Questoris Knight Crusade Army List included in the same book and the Titans from the Mechanicum Taghmata Army List. The Knight Crusade gets the Titans.

Crusade Imperialis does _not_ say anything about additional LoW choices for Imperialis Militia and Cults. On the one hand, the book specifies this for the Auxilia and Knight armies; since it doesn't give any additional LoW for Militia and Cults, one would assume that they don't have any. On the other hand, the explanation for using non-30k Super-Heavies is that they represent the vast variety of unusual vehicles that were present; this justification would apply more to the Militia and Cults than anyone else.

[The reason for my confusing initial post is that I was thinking, "Marines can take anything without a 30k profile. Baneblades have 30k profiles, so they're not included in this." Sorry for the mistake.]

**Comment by capitaladot** [comment]
No worries; I think the real debate is, does the version of this rule
in AoDAL supersede those in MTAL and CIAL? I say, probably not, unless
FW FAQs it or puts it in a black book. I don't count FW customer
service emails, as you might as well ask your nearest housepet.

**Comment by akujiro** [comment]
They not supersede they just adding new. If you can take banblade in militia army why you cant take for example another pattern of that?
Crusade Imperialis does not say anything about additional LoW choices whell its not but AoDAL says and again rules not says that is only for legions. 
Well i think you can of course don't count FW customer
service emails, you of course, can contact forgeworld support yourself.  
Or just wait new hh rulebook i guess.
I don't think ff will faq anything or it will be new blackbook with militia lists. They added rule in latest list and it now about community how to use this rule and i dint see any problem with militia player will use for example stormsword as legion player dose.
 I just show you that rule exists.

**Comment by capitaladot** [comment]
You are missing the point. The debate is, does this version of the rule from Age of Darkness Army List replace the version that appeared in Crusade Imperialis. The effect of the rule is allowing  selecting additional LoW. 

I say, the version in Crusade Imperialis is not replaced without a FAQ or a new global (covering the whole game system)  version in a new black book, because Age of Darkness Army List does not alter Crusade Imperialis.

**Comment by akujiro** [comment]
Well can't angry with you , legions book comes later and just have newer version  of this rule. So it logically could replace older one in imperial ice book

**Comment by TomTheHand** [comment]
But the rule in AoDAL says you can take a Space Marine crew for 15 points, providing BS 4; this implies that the rule is meant to apply to Space Marines. Similarly, in the Mechanicum Taghmata Army List's version of the rule it says you can take Autokrator Control, granting BS 4 and Blessed Autosimulacrum, for 20 points. That rule, therefore, is Mechanicum-specific and was not intended to replace previous books (such as the Marines' earlier Crusade Army List). These rules appear to be written to apply specifically to the army covered by the book, not all armies.

**Comment by alphalas** [comment]
^this. AoDAL *only* applies to SM legion lists - there is no carryover unless *SPECIFICALLY* identified. There is no such clause, ergo this is an invalid bugrep.

**Comment by akujiro** [comment]
"But the rule in AoDAL says you can take a Space Marine crew for 15 points, providing BS 4; this implies that the rule is meant to apply to Space Marines"
Well rule apoint this :
When used in conjunction with this army list, these vehicles may be further
modified by the following upgrades:
Space Marine Crew (Super-heavy Tanks only): +15 points
Battle Servitor Control (Flyers only): +15 points. If taken as an option
for a Sub-orbital Strike Wing, then all the Flyers in the wing must be so
upgraded.
If you use with othere list no upgrades

But i got you point this is really weird rule in legion list must applay only to legions. It just because there is no central book for all armies. It just easy can be clarify by forgeworld. So we can contact support or just wait promised aod rulebook.

For my group we have forgeworld mail for now is enough. Especialy there are not many militia list anyway. Until new rules will out as basicly all hh system is outdate.

In othere hand from developer pov maybe you right to wait some clarification from forgeworld.
