### ISSUE TITLE
Add unit - New Sicarans

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#1106]
- [x] [HH_Sicaran Omega Tank Destroyer.pdf](https://github.com/BSData/horus-heresy/files/1293391/HH_Sicaran.Omega.Tank.Destroyer.pdf)

- [x] [HH Legion Arcus Strike Tank.pdf](https://github.com/BSData/horus-heresy/files/1296800/HH.Legion.Arcus.Strike.Tank.pdf)

**Comment by TomTheHand** [comment]
I wonder if the Venator, Punisher, and Omega should be combined with the regular Sicaran, so they're just weapon options instead of separate units. You might have something like the following:

Variant:
Sicaran Battle Tank (Twin-linked Accelerator Autocannon) (no cost)
Sicaran Punisher Assault Tank (Punisher Rotary Cannon) (15 pts)
Sicaran Venator Tank Destroyer (Neutron Beam Laser) (25 pts)
Sicaran Omega Tank Destroyer (Omega Plasma Array) (70 pts)

**Comment by alphalas** [comment]
Only if FW arranges it that way - otherwise it adds unnecessary constraints for RoWs that require/allow only plain sicarans - we already discussed this on gitter.

**Comment by capitaladot** [comment]
Indeed, @zopha and I had just the same discussion earlier today, and I
agree completely with @alphalas on the matter and reasoning.

**Comment by TomTheHand** [comment]
100% understood. It could possibly also be confusing for users: "I want a Venator, but the only option in my Heavy Support is for a regular Sicaran!" I'm just brainstorming for things that would (presumably) save memory so the list will run better on various devices.

**Comment by alphalas** [comment]
Understood; however, brainstorming should be on gitter, not here

**Comment by zopha** [comment]
It would be great to add them that way but the way they have some RoW set up makes it difficult. Perhaps the next red book will clear it up and allow sicaran squads of different loadouts.

The sicarans aren't too bad, they're mostly linked entries so not too large, any space saving would be awesome thought. To lessen potential future work I've set up the turrets as shared entries with their own points cost just like you've outlined above.

**Comment by capitaladot** [comment]
@TomTheHand gitter.im/BSData/horus-heresy
