### ISSUE TITLE
HH V1 - Missing profiles for Heavy Support Choices (non-legion specific)

### ISSUE THREAD

**Issue by archonkain** [BSData/horus-heresy#1165]
(just from the red book, and no guarantee of being complete)

**Extra Armor:**
(I have listed both versions, so you can choose which way to go, I think listing it in the wargear profile is better personally)
_Just linked to the universal rules:_
- [ ] Caestus Assault Ram
- [ ] Deredeo Pattern Dreadnought
- [ ] Land Raider Achilles
- [ ] Sicaran Arcus Strike Tank
- [ ] Sicaran Battle Tank
- [ ] Sicaran Omega Tank Destroyer
- [ ] Sicaran Punisher Assault Tank
- [ ] Sicaran Venator Tank Destroyer
- [ ] Spartan Assault Tank

_Linked in the profile section_
- [ ] Achilles-Alpha Pattern Land Raider
- [ ] Basilisk
- [ ] Medusa
- [ ] Whirlwind
- [ ] Land Raider Phobos
- [ ] Land Raider Proteus
- [ ] Predator Tank
- [ ] Vindicator Siege Tank
- [ ] Whirlwind Scorpius

_Not linked at all_
- [x] Leviathan Siege Dreadnought

**Armoured Ceramite:**
(I have listed both versions, so you can choose which way to go, I think listing it in the wargear profile is better personally)
_Just linked to the universal rules:_
- [ ] Caestus Assault Ram
- [ ] Deredeo Pattern Dreadnought
- [ ] Fire Raptor Gunship
- [ ] Land Raider Phobos
- [ ] Land Raider Proteus
- [ ] Leviathan Siege Dreadnought
- [ ] Malcador
- [ ] Predator
- [ ] Sicaran Arcus Strike Tank
- [ ] Sicaran Battle Tank
- [ ] Sicaran Omega Tank Destroyer
- [ ] Sicaran Punisher Assault Tank
- [ ] Sicaran Venator Tank Destroyer
- [ ] Spartan Assault Tank
- [ ] Vindicator Siege Tank

_Linked in the profile section_
- [ ] Land Raider Achilles - which shouldn't have it at all anyways

---by unit---

Achilles-Alpha Land Raider: 
- [ ] shatter shells for quad launcher are at a cost (10 points), the book lists them as auto included.
- [ ] the volkite culverns are supposed to be twin-linked. They are listed as twin-linked on the roster generation screen, but not the view/print roster page. the twin linked rule is added to the bottom
- [ ] Machine Spirit - it is listed, and in the rules part it says it confers power of the machine spirit rule, but that isn't linked.
- [ ] Enhanced Ferromantic Rites - just linked to the universal rules section, not linked to a profile in the wargear section

Legion Caestus Assault Ram
- [ ] Machine Spirit - it is listed, and in the rules part it says it confers power of the machine spirit rule, but that isn't linked.

Jetbike Sky Slayer Support Squadron
- [ ] Chainsword or Combat Blade - missing, the checkbox to add it does not add any profile or rules, just the name under wargear

Kharybdis Assault Claw
- [ ] Melta-Ram - these are listed at the bottom where universal rules are, not in the profile for the unit
- [ ] Heat Blast - these are listed at the bottom where universal rules are, not in the profile for the unit

Land Raider Achilles
- [x] Ferromantic Invulnerability - it links the rule at the bottom, but doesn't list it for the vehicle

Land Raider Phobos
- [ ] Assault Vehicle - it links the rule at the bottom, but doesn't list it for the vehicle
- [ ] Machine Spirit - it is listed, and in the rules part it says it confers power of the machine spirit rule, but that isn't linked.
- [ ] Hull Mounted Twin Linked Heavy Bolter - this is missing a link or profile

Leviathan Pattern Siege Dreadnought
- [ ] Attacks - it does not reduce the number of attacks as close combat arms are replaced with a ranged weapon
- [ ] Smoke Launcher - missing
- [ ] Searchlight - missing
- [ ] Frag Grenades? - missing
- [x] Extra Armour - not linked at all

Malcador
- [ ] Hull Mounted Heavy Bolter - it is listed as an option that has to be selected when it is auto-included on the profile in the book, perhaps set it as the default selection for the options menu?

Sicaran Battle Tank
- [ ] Heavy Bolter - missing

**Comment by capitaladot** [comment]
So, having the rule at the bottom isn't a bug.

To have linked rules in the unit entry, several steps are required. Adding
in extra containers for every rule link bloats the file and requires
constraints (min1, max1) . The file is already too large due to the
complexity of the HH Astartes rules set.

On Oct 29, 2017 6:46 PM, "archonkain" <notifications@github.com> wrote:

(just from the red book, and no guarantee of being complete)

*Extra Armor:*
(I have listed both versions, so you can choose which way to go, I think
listing it in the wargear profile is better personally)
*Just linked to the universal rules:*

   - Caestus Assault Ram
   - Deredeo Pattern Dreadnought
   - Land Raider Achilles
   - Sicaran Arcus Strike Tank
   - Sicaran Battle Tank
   - Sicaran Omega Tank Destroyer
   - Sicaran Punisher Assault Tank
   - Sicaran Venator Tank Destroyer
   - Spartan Assault Tank

*Linked in the profile section*

   - Achilles-Alpha Pattern Land Raider
   - Basilisk
   - Medusa
   - Whirlwind
   - Land Raider Phobos
   - Land Raider Proteus
   - Predator Tank
   - Vindicator Siege Tank
   - Whirlwind Scorpius

*Not linked at all*

   - Leviathan Siege Dreadnought

*Armoured Ceramite:*
(I have listed both versions, so you can choose which way to go, I think
listing it in the wargear profile is better personally)
*Just linked to the universal rules:*

   - Caestus Assault Ram
   - Deredeo Pattern Dreadnought
   - Fire Raptor Gunship
   - Land Raider Phobos
   - Land Raider Proteus
   - Leviathan Siege Dreadnought
   - Malcador
   - Predator
   - Sicaran Arcus Strike Tank
   - Sicaran Battle Tank
   - Sicaran Omega Tank Destroyer
   - Sicaran Punisher Assault Tank
   - Sicaran Venator Tank Destroyer
   - Spartan Assault Tank
   - Vindicator Siege Tank

*Linked in the profile section*

   - Land Raider Achilles - which shouldn't have it at all anyways

---by unit---

Achilles-Alpha Land Raider:

   - shatter shells for quad launcher are at a cost (10 points), the book
   lists them as auto included.
   - the volkite culverns are supposed to be twin-linked. They are listed
   as twin-linked on the roster generation screen, but not the view/print
   roster page. the twin linked rule is added to the bottom
   - Machine Spirit - it is listed, and in the rules part it says it
   confers power of the machine spirit rule, but that isn't linked.
   - Enhanced Ferromantic Rites - just linked to the universal rules
   section, not linked to a profile in the wargear section

Legion Caestus Assault Ram

   - Machine Spirit - it is listed, and in the rules part it says it
   confers power of the machine spirit rule, but that isn't linked.

Jetbike Sky Slayer Support Squadron

   - Chainsword or Combat Blade - missing, the checkbox to add it does not
   add any profile or rules, just the name under wargear

Kharybdis Assault Claw

   - Melta-Ram - these are listed at the bottom where universal rules are,
   not in the profile for the unit
   - Heat Blast - these are listed at the bottom where universal rules are,
   not in the profile for the unit

Land Raider Achilles

   - Ferromantic Invulnerability - it links the rule at the bottom, but
   doesn't list it for the vehicle

Land Raider Phobos

   - Assault Vehicle - it links the rule at the bottom, but doesn't list it
   for the vehicle
   - Machine Spirit - it is listed, and in the rules part it says it
   confers power of the machine spirit rule, but that isn't linked.
   - Hull Mounted Twin Linked Heavy Bolter - this is missing a link or
   profile

Leviathan Pattern Siege Dreadnought

   - Attacks - it does not reduce the number of attacks as close combat
   arms are replaced with a ranged weapon
   - Smoke Launcher - missing
   - Searchlight - missing
   - Frag Grenades? - missing
   - Extra Armour - not linked at all

Malcador

   - Hull Mounted Heavy Bolter - it is listed as an option that has to be
   selected when it is auto-included on the profile in the book, perhaps set
   it as the default selection for the options menu?

Sicaran Battle Tank

   - Heavy Bolter - missing

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/1165>, or mute the thread

**Comment by alphalas** [comment]
@capitaladot I think what he wants is Profiles vs rules, ALA 40k files; so that everything shows in the unit entry (which only changes the size of the output, not the data)

**Comment by archonkain** [comment]
I would prefer it to print in the profile section personally, but right now with Extra Armour it is about 50/50 where it is put.  Regardless of where you put the rule (in the unit profile, or bottom of the roster) shouldn't each unit put it in the same place?

There are a few units that are just strait up missing parts however where it isn't in the rules or the profile.   Such as the Leviathan, or Machine Spirit never giving the text for Power of the Machine Spirit.

**Comment by alphalas** [comment]
I agree, rules as profiles is a much nicer layout; also yes, there should be more consistency with how they’re implemented.

**Comment by zopha** [comment]
There has been a little discussion on gitter.im about this. Here is a test example with one unit as it is now and one with profiles instead of rules. It should be using the default output of battlescribe, if it is not please let me know the correct defaults.

[Leviathan Test 1.pdf](https://github.com/BSData/horus-heresy/files/1433362/Leviathan.Test.1.pdf)
