### ISSUE TITLE
command squad jump packs are 15pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1216]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** The calculations are way off. For instance on a command squad jump packs are 15pts a piece. Yet for my command squad of 5 it calculates it at 100pts. 15 x 5 =75 not 100.

**Comment by zopha** [comment]
This will be fixed in the next release for Jump Pack, Bikes and Jetbikes on the command squad. 

If there are other instances please let us know, we'll get to them eventually but due to the extremely large amount of units to cover in the HH system they may not be found until someone highlights the issue.

**Comment by zopha** [comment]
Fix is currently in a branch that can't be merged so I'll work on it again.

**Comment by capitaladot** [comment]
Found this wasn't fixed, so fixing.
