### ISSUE TITLE
Terminator Legion Command Squad - Incorrect cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1227]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The points values for a Terminator Legion Command Squad seem to be incorrect. When you select what type of Terminator armour they are wearing, it adds +35pts to the squad total even though this has already been factored in by choosing Terminator Legion Command Squad and not Legion Command Squad. Thanks.

**Comment by capitaladot** [comment]
Thanks for the report. Will double check what the app is mathing.

On Jan 20, 2018 7:55 PM, "BSDataAnon" <notifications@github.com> wrote:

*File:* (HH) Legiones Astartes - Crusade Army List.catz

*BattleScribe version:* 2.01.12

*Platform:* iPhone / iPod / iPad

*Dropbox:* No

*Description:* The points values for a Terminator Legion Command Squad seem
to be incorrect. When you select what type of Terminator armour they are
wearing, it adds +35pts to the squad total even though this has already
been factored in by choosing Terminator Legion Command Squad and not Legion
Command Squad. Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/1227>, or mute the thread
