### ISSUE TITLE
In the legions Astartes attack bike entry, an error is returned that attack bikes should not have the Legion Astartes rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1237]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** Yes

**Description:** In the legions Astartes attack bike entry, an error is returned that attack bikes should not have the Legion Astartes rule

**Comment by capitaladot** [comment]
Thanks for the report. Will fix.

On Jan 25, 2018 1:16 PM, "BSDataAnon" <notifications@github.com> wrote:

*File:* The Horus Heresy.gstz

*BattleScribe version:* 2.01.14

*Platform:* Android

*Dropbox:* Yes

*Description:* In the legions Astartes attack bike entry, an error is
returned that attack bikes should not have the Legion Astartes rule

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/1237>, or mute the thread

**Comment by capitaladot** [comment]
Marking as Choice because Attack Bikes should not have a Legiones Astartes selection.
