### ISSUE TITLE
Allies Force Org Chart in both astartes and mechanicum are giving error of "too many selections from allied detachment (maximum 0)" when any unit is added to the detachment.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1263]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Allies Force Org Chart in both astartes and mechanicum are giving error of "too many selections from allied detachment (maximum 0)" when any unit is added to the detachment.

**Comment by capitaladot** [comment]
Which parent Force Org? Which Rite of War?

**Comment by HrothgarTheBold** [comment]
Age of Darkness parent force org for both factions,and no RoW for astartes.

**Comment by zopha** [comment]
Looks like it's the And All Child Sections on the this

![Imgur](https://i.imgur.com/4Jue9Hf.png)

And the constraint is present in the other army files.

Not sure why it's enabled now, perhaps due to a battlescribe update... might be easier, in the long run, to remove it and let players self-regulate.

**Comment by capitaladot** [comment]
Weird. That doesn't seem like that should do what it seems to be doing!
