### ISSUE TITLE
Wolfkin of Russ are a separate HQ choice

### ISSUE THREAD

**Issue by caraya** [BSData/horus-heresy#1266]
I'm getting an error about missing compulsory HQ Choices when using Leman Russ and the wolfkin of Russ. The book states that:

**The Wolf-kin of Russ may only be taken in an army if Leman
Russ is also present. If they are chosen as part of the army, they
are treated as a HQ choice so far as any special rule, objective
or mission is concerned, but do not take up slots on the Force
Organisation chart.**

My understanding is that this means I could take them as the second compulsory HQ choice. The rule seems to contradict itself but I haven't found an FAQ to confirm it either way

**Comment by capitaladot** [comment]
Sorry, have to disagree. Operative phrase: "*but do not take up slots on
the Force Organisation chart."*
*This means they are the same HQ choice as Russ pre-game, but are a Unit
once the game begins (at  Deployment) , similar to a Command Squad
/Bodyguard or members of a Dreadnought Talon or Strike Wing. *

**Comment by caraya** [comment]
The wording of the rule is confusing. If **they are treated as an HQ choice so far as any special rule, objective or mission is concerned** then they should count as an HQ choice for filling compulsory requirements for army composition.  

The wording for command squad is different. 

I'll ask Forgeworld for clarification and keep this open until I hear from them.

**Comment by alphalas** [comment]
It’s a very simple answer – if they do not take up a force org slot, they do not count as a compulsory choice needed to fill that force org slot.

**Comment by capitaladot** [comment]
Carlos,

I agree it is a bit confusing; FW's treatment of slots that are not slots
is tricky, especially things that count differently (as FoC
choices/slots/Compulsory requirements) before game (during list building)
and during/after game (for scoring / kill points). Techmarine Covenants,
Apothecarion Detachments, Dreadnought Talons, Assault Wings, War Engine
Detachments and Bodyguards for Master of the Legion (command squads and
some Legion specific units), and the Wolfkin all present such cases.

My view is that list building requirements can only apply before the game
begins, simply because losing units to casualties would otherwise cause
one's list to become illegal as the game proceeds. Thus, for unit counting
purposes,  we have at least two phases of game play (three in some missions
that score at the end) : before the game begins, and deployment and
thereafter (some of the aforementioned FoC choices split up into discrete
Units at Deployment; others split on the first controlling player turn).

**Comment by caraya** [comment]
Since @alphalas made the pronouncement and closed the issue then we're done. No need to keep discussing it.  

As I said, I'll ask Forgeworld and see what their answer is.

**Comment by capitaladot** [comment]
Don't bother emailing them. FW Customer Service is not a trustworthy,
consistent or authoritative source. Wait for a FAQ or GTFO. ;)

**Comment by caraya** [comment]
Wasn't going to email customer service... I agree that they may be good gamers but don't make the rules :)
