### ISSUE TITLE
Space Wolves Bugs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1273]
- [x] Space Wolves independent characters can no longer select Frost Weapons... But Grey Slayer Huscarls can...
- [x] And Huscarls can't replace their bolt pistol and chainsword with Twin Lightning Claws (specifically the bolt pistol entry has to be filled); 
- [x] Selecting Aether-rune armor or the Mantle Of Ultramar prevents Legion Praetors from exchanging their weapons (results in error "too many selections of 'replace (insert weapon here) with:' "

**Comment by capitaladot** [comment]
Duplicate

**Comment by samb1892** [comment]
Grey slayer Huscarl does not have access to combat shield option.

**Comment by samb1892** [comment]
Speaker of The dead (priest of debris) does not have access to Deathsworn command squad option.

**Comment by samb1892** [comment]
Speaker of The dead (priest of Fenris) does not have access to Deathsworn command squad option.

**Comment by zopha** [comment]
Thanks @samb1892 ! Since there's a pull request open for the original issues I've opened #1284 for the additional ones you've added. If you find more just add them in there, please.

**Comment by samb1892** [comment]
Will do! I'm new to all this. So apologies.

Sent from my iPhone

On 13 Mar 2018, at 08:25, zopha <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @samb1892<https://github.com/samb1892> ! Since there's a pull request open for the original issues I've opened #1284<https://github.com/BSData/horus-heresy/issues/1284> for the additional ones you've added. If you find more just add them in there, please.
