### ISSUE TITLE
Wargear and Weapons profiles are now missing.

### ISSUE THREAD

**Issue by Jesse1220** [BSData/horus-heresy#1280]
After recently updating catalogs, I noticed any new Legiones Astartes units I add to a list no longer have wargear or weapons profiles when I view the roster. I've tried several options, but they don't appear. Have they been removed?

**Comment by capitaladot** [comment]
They haven't been removed, no. I have seen this BattleScribe bug a few
times on Android but it seems to appear inconsistently.

On Mar 6, 2018 4:37 PM, "Jesse1220" <notifications@github.com> wrote:

After recently updating catalogs, I noticed any new Legiones Astartes units
I add to a list no longer have wargear or weapons profiles when I view the
roster. I've tried several options, but they don't appear. Have they been
removed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/1280>, or mute the thread

**Comment by zopha** [comment]
Battlescribe can do this sometimes when it hits a memory limit.

Check that low memory mode isn't enabled. It's menu option in android.
![Imgur](https://i.imgur.com/JlOALzG.jpg?1)

Also check Customize output on View Roster and make sure Profiles and Rules and Summary aren't set to No Profiles or No Rules.
![Imgur](https://i.imgur.com/n9vIYBG.jpg?1)

If you've done both then clear out your catalogue data and see if that helps. You can delete data from the menu in Manage Data. Take a look at this: https://battlescribe.net/?faq=refreshData

**Comment by Jesse1220** [comment]
Thank you, the Low memory mode was checkmarked, this was the issue.
