### ISSUE TITLE
Some minor issues, and some others too.

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1472]
Armillus Dynat & Autilon Skorr: Should have Artificer Armor as default. (you have to select it for some reason)

Power Glaive: is showing Strength as "User/1" should be: "User/+1"
Also, power Glaive is available for bodyguards, and since they arent characters, it shouldnt be.
Rite of War: The Sagyar Mazan, not showing up for whites scars (just for Shattered Legions)

The Nemean Reaver: Has a Master Crafted Bolt Pistol that is NOT in his profile.

Qin Xa and Raldaron have had their rules released in the weekender, maybe we can put them up already? their pre-released profiles are annexed below.

![qin xa](https://user-images.githubusercontent.com/21247755/52190774-23723180-2828-11e9-804b-dc885596b8b0.jpg)

![raldoron](https://user-images.githubusercontent.com/21247755/52190786-2c630300-2828-11e9-9829-97d69b987a48.jpg)

**Comment by Mayegelt** [comment]
Thanks for the report. Had a bit of a busy week with Worky and stuff after having gone to the Weekender. Was going to add the new characters in today anyway :) But thanks for catching the other issues.

I fixed Armillus Dynat & Autilon Skorr. Seems to have been a remnant of an older build that had them with an option to take it, rather than just included by default. So no selection needed now.

I have changed Power Glaive to User/+1

Redid the selections for power weapons to stop terminator command squads from taking Power Glaives. 

Rite of War: The Sagyar Mazan IS Shattered Legion only. as per the picture i linked.
![image](https://user-images.githubusercontent.com/20280410/52532424-dc4ed980-2d1c-11e9-90d2-356f52f0f141.png)

Added Nemean Reaver Master Crafted Bolt Pistol.

Qin Xa and Raldaron Added

**Comment by Tomakokamikaze** [comment]
oh, than, also, Scimitar Jetbikes for bodyguards are not showing any weapons

**Comment by Mayegelt** [comment]
@Tomakokamikaze as in not showing heavy bolter or something else?

**Comment by capitaladot** [comment]
Can only take a Heavy Bolter.

**Comment by Mayegelt** [comment]
@capitaladot i was wondering if he had found that a weapon option for the unit was not there. Latest update to my pull request has added stats for the Heavy Bolter in (of course salamanders can exchange for Heavy Flamers)

**Comment by capitaladot** [comment]
Keen!

**Comment by Mayegelt** [comment]
@capitaladot fixed :)

**Comment by Mayegelt** [comment]
Able to be closed now @capitaladot
