### ISSUE TITLE
(HH) Legiones Astartes - Crusade Army List issues

### ISSUE THREAD

**Issue by Toreador13** [BSData/horus-heresy#1508]
Land Raider Phobos does not have a default hull mounted twin-linked heavy bolter listed as part of it's profile.  

Aether Rune armour has some odd issues in the Priest of Fenris selectors. When hovering over selection it shows the bolt pistol profile, and aether rune armour must be selected again after the first selection (probably more of an application issue. )  Should the profile of the priest of fenris show a wound increase with the aether armour selection? I see that it changes the armour save, but should W also be added?

**Comment by Mayegelt** [comment]
Will be fixed in my latest pull request.

The stat increase from items like Aether Rune Armour and Digital lasers are not put onto the profiles of the characters by the application. We could do this for each case, but this could also cause confusion for those who are looking at the item description, so could end up with a stat profile upgrade then applying the upgrade again.
