### ISSUE TITLE
Space Wolves priest of fenris command squad deathsworn

### ISSUE THREAD

**Issue by Camyron** [BSData/horus-heresy#1554]
Priests of fenris with the Speaker of the Dead subtype should be able to take a deathsworn squad as a command squad.

**Comment by Camyron** [comment]
Deathsworn can currently be taken as command squads for any space wolf motl, even though they cannot be joined by any independant character other than speakers of the dead.

**Comment by Mayegelt** [comment]
Ok this is a really odd one.
As you have put, it seems to give any Space Wolf character with Master of the Legion the ability to take Deathsworn as a Command Squad. This shouldn't be there.

However it says that a Speaker of the Dead can buy one instead of a command squad.
"Cult of Morkai
Units of the Deathsworn may not be joined by Independent Character models other than Priests
of Fenris. In addition, Priests of Fenris with the Speaker of the Dead sub-type may take a unit of
Deathsworn instead of the usual Command Squad."
However a Speaker of the Dead does not have Master of the Legion to give him access to a command squad as a Retinue, unless as per retinue rules he is also named as the armies Warlord. 
So given him the optioned to be tagged as warlord if he wants that Deathsworn Command Squad.

**Comment by zopha** [comment]
It should be live for devices to update in 12-24 hours, depending on Appspot. If you get the updated file please test and reopen if the issue is still present.
