### ISSUE TITLE
Solar Auxilia Missing Profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#156]
**File:** (HH) Solar Auxilia - Crusade Army List.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi, I've noticed when creating Solar Auxilia lists that when I got to view my roster by clicking the eye icon, a lot of the info is missing. 
Especially weapon profiles. 
For example;
- [ ] Flamer Section - Doesn't show profiles for Flamers. 
- [ ] Doesn't show Wargear for Sergeant (Flamer, Pistol, CCW) or 
- [ ] his 9 men (Flamer, Laspistol) 
Would be really helpful if this could be added. 
For Example;
Rapier Battery Guns - Doesn't show profiles for selected Rapier Weapon. 
I.E. 
- [ ] Quad Mortar, 
- [ ] Multi-Laser,
- [ ] Quad Heavy Bolter
- [ ] Doesn't show wargear or
- [ ] stats for the 2 man crew etc. 

Could these missing bits of info/profiles and options be added in please? 

Thank you, 
Michael.

**Comment by Millicant** [comment]
Some of this can be handled, but many of the weapon profiles are left out on purpose.  This is meant to replicate most accurately the organization of the Forgeworld books.  It also serves as my subtle way of encouraging users to own the books, rather than rely on the catalogues as a replacement.   I'm afraid this would mean that I would be committing to months worth of work re-writing every entry in each catalogue.  At this point, I'm sticking to the way I started.  I apologize, I know that this can be inconvenient, but please remember this is intended as a list-building aid, nothing more.  

Lastly, the 2-man rapier crew's profile is already listed.
