### ISSUE TITLE
Damocles Command Rhino - not hiding when Orbital Assault RoW selected

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#1576]
It can still be added without errors when Orbital Assault RoW is chosen. Either as a separate HQ unit or dedicated transport for Ultramarines.

Tested this myself after finding the issue on Reddit https://www.reddit.com/r/BattleScribe/comments/dbe4ya/damocles_command_rhinos_and_orbital_assault_row

**Comment by boada** [comment]
Awesome. I posted the issue on Reddit and then got around to trying to report it here. Thanks for beating me to it @zopha

**Comment by Mayegelt** [comment]
As far as i know, i don't think the RoW hides any units currently.
The issue is that a fair number of things can't be taken due to not having deep strike.
A big issue for coding it is that something like say Breacher squads can't naturally be taken for it due to no ability to take a Rhino (to give them option for Drop Pod). But they could go in a Storm Eagle or Anvillus, Kharybris or Caestus...
If you can compile a list of everything that 100% can't be taken, i will try to mark them all as hidden. But i think even this will cause difficulty, as like the example above, they could end up taking more units that can't deep strike, without giving them transports that can.

**Comment by boada** [comment]
@Mayegelt Could Battle Scribe issue a warning when a unit without the deepstrike rule has been taken? Then we wouldn't need to hide anything but the user would still know that the list might not be valid if they've not accounted for everything.

Maybe something like. "All units are required to Deep Strike while the Orbital Assault RoW is active. You currently have XXX units which cannot Deep Strike naturally."

**Comment by Mayegelt** [comment]
@boada sadly I think the program is not clever enough to do that. Or at least it would just flag errors for it continually. Especially when units can sometimes take deepstrikes. This can happen especially with things like Apothecary or Independent Characters, which may join units.
I think it's just a case that people will need to be careful that they read the RoW and follow the guidelines that are printed.

**Comment by capitaladot** [comment]
@Mayegelt this would be possible if the Deep Strike rule was contained within a SharedEntry.

**Comment by Mayegelt** [comment]
Long time for me to answer that question (basically didn't see the response) I don't thing this one is possible even with new things.
