### ISSUE TITLE
Legiones Astartes Kyzagan not showing all its gear/rules, and some Shattered Legions adjustments

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1645]
--Qin Xa
I might be wrong, but I believe his bodyguards can take any pattern of terminator armor
And also, I think your warlord needs to be with terminator armor/jump pack/bike/jetbike for the command squad to get it

--Kyzagan

Rules might be listed on the bottom, but not in the unit.

• Two reaper autocannon (only showing one in the list mode)

Special Rules 

• Deep Strike (showing OK)

• Outflank (not showing at all)

• Strafing Run (Listed in the bottom but not in the unit)

• Grav Backwash (not showing at all)

*Searchlight Option not showing anything when selected)

--Shattered Legions:

When selecting Shattered Legions and White Scars, you no longer need to obey the rule of having more fast attacks than heavy support.

Golden Keshig, Ebon Keshig, Kyzagan and Falcon's Claws should already come with LA: White Scars when chosign Shattered Legions

Alpha Legion: If the Warlord is not an Alpha Legionaire there is no Mutable tactics with Shattered Legions

No Martial Hubris for Alpha Legion in Shattered Legions

**Comment by Mayegelt** [comment]
I will try to look in to these during the week.

**Comment by Mayegelt** [comment]
Ok. Sorry for the delay. Various other things pulling my time away from me.

Qin Xa can only have Tartaros Armoured Bodyguard. The latest FAQ says "If this option is chosen then every member of the squad must be upgraded to the Terminator Bodyguard Wargear selection and has access to the following options, rather than those shown previously (the same type of Terminator armour must be chosen for the entire unit):" As he has to be in the unit. I assume he will also have to be in the same armour as they are. And he comes in Tartaros.

The formating for the Kyzagan is the same as for the Javalins. The Autocannons should display they have 2 of them, and show 2 of them as well as per this picy from desktop version.
![image](https://user-images.githubusercontent.com/20280410/73357477-595bc180-4294-11ea-81f6-cbd578a214cd.png)
Link to the profile of searchlight added. It seems it was missing from a couple of entries. So fixed it.

Shattered Legion stuff. The Whitescars limitation should be removed. But also looks like there are other issues with this type of thing as well. "Flesh Over Steel" for Ravenguard (not shattered legion) is not being checked in any way either. So i think i will put this into a new bug to be fixed, as this might require a bit of work to sort all of these out. However have fixed the Whitescar one.

Added additional option to Alpha Legion Mutable Tactics, to have a selection that is only visible when using Shattered Legions to be clickable for if your Shattered Legion does not have an Alpha Legionnaire as its Warlord. And adding reference in the rules saying this within the rules.
