### ISSUE TITLE
Dreadwing Interemptor Transport

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1666]
As of now the Dreadwing Interemptors can only pick a land raider proteus when at exactly 10 models, however it was intended

 to be when they have 10 models or less. 
See evidence attatched

![interemptor rules clarification](https://user-images.githubusercontent.com/61972913/76211521-5e4e5200-61fe-11ea-8b73-018279e5607e.JPG)

**Comment by Mayegelt** [comment]
Currently it is listed as
"An Interemptor squad numbering 10 models may take a Land Raider Proteus as a Dedicated Transport."
Until they update the download (or book) it's not official, even with an email from FW.
Otherwise I've had emails from FW saying conflicting versions of the same thing, such as Nightlords - "Talent for murder" adds 1 to the dice roll of hit and wounds. Meaning technically they get Precision Stikes / Rending / Murderous Stikes on 5s if they have those rules as well.

**Comment by Mayegelt** [comment]
As said above, until download of book changes it. It has to be what was on them.
