### ISSUE TITLE
Assault Sergeants with no Melta Bombs? And Praetor with no Divining Blades?

### ISSUE THREAD

**Issue by WildestDrake** [BSData/horus-heresy#1688]
Heya, took a look at my list after the latest update, and the two above things reported as errors, and yet I haven't been able to figure out why or what I need to do _instead_ of the way I did it before in order to give my Praetor Divining Blades, and to give my Assault Sergeants Melta Bombs.

I've also tried to look for any errata or rule changes but I've had no luck in this search.

What's going on? Is this a bug or an intended change/feature?

**Comment by WildestDrake** [comment]
When I take Divining Blades, Empyrial Lance also disappears from options until I select something else in the same options on a praetor.

**Comment by Mayegelt** [comment]
Hiya, it looks like the latest update to battlescribe on Android, has caused a couple of issues. It seems to work perfectly fine on desktop.
The reason why the Empyrial Lance disappears when you select Divining blade, is because you can only have one Psyarkana per person.
The easiest way to achieve this when coding it it was as both of those are replacements as weapons I needed to put a hide function if the others were selected or if another piece of Psyakana was selected. All the Psyakana have these hide functions.

hopefully I should be able to make a resolution to the sergeant and divining blade stuff if it proves to be an ongoing issue.

**Comment by Mayegelt** [comment]
Hopefully should be fixed now (or when pull goes live, but I'll leave this here just in case

**Comment by Mayegelt** [comment]
It seems to be fixed so I will close this.
