### ISSUE TITLE
Solar Auxilia: major abandonment issues

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1740]
Dont know about desktop, but this are the issues I'm seeing in my Iphone:

General -> Weapon Profiles not listing their special rules like _concussive_ and such...
Disciplined Command - Not showing anything for it
Void Hardened - Rule not showing anywhere
Shroud Bombs - Profile not showing
Power Weapons - not showing options

Strategos -> No Plasma Pistol option

Lord Marshal Ireton MaSade -> Hatred (Traitor Forces) not saying what hatred does

Auxilia Primaris-Lightning Strike Fighter -> Twin-linked Autocannon/Twin-linked Missile Launcher/Twin-linked Missile Launcher with Rad Missiles/ Twin-linked Multi-laser ----->>> Weapon Profiles not showing

Dracosan Armored Transport -> Twin Linked Lascannon profile not showing
->Demolisher Cannon profile not showing
->Pintle mounted Multi-Laser or Heavy Flamer choice not enabled and profiles not showing
->Dozer Blade and other such rules not showing their effects
->Not showing Transport Capacity (and not halving it when the Demolisher Cannon is chosen)
->Maybe move it to inside the infantry choice as a Dedicated Transport)

Velataris Storm Section -> Melta Bomb Profile Not showing
-> when changing to power axes, sarge doesnt get one

Household Retinue Squad -> Not showing Laspistol profile
->Not showing granades profiles
->Not showing Close combat Weapon Profiles
->Not showing Power Axes Profiles when Chosen
-> when changing to power axes, sarge doesnt get one

Thats all I found so far, thanx

**Comment by capitaladot** [comment]
We haven't been back over this file since the original half-assed entry of
it, so this hit list is helpful!

**Comment by Tomakokamikaze** [comment]
I see you guys implementing things like mournival event rules (wich is cool), but maybe you are neglecting Solar Aux and Imperial Aux

**Comment by alphalas** [comment]
~~especially when it’s fan rules vs official rules on a repo that is only supposed to be official rules but that’s not my business anymore~~

**Comment by Mayegelt** [comment]
Basically didn't know a load of this stuff was missing. Thanks for the comprehensive guide flagging up the issues. I'll get onto them.

**Comment by Mayegelt** [comment]
@Tomakokamikaze  Ok quick update. I think I've just got them all, though might have missed one, so if you could recheck on the update to v68 of the solar list.

**Comment by Tomakokamikaze** [comment]
@Mayegelt I will check it, but before you close, you might wanna check the LoW entries, I’m pretty sure things there are outdated. Also, are Rapiers relentless? Can they move and shoot heavy weapons without issue?

**Comment by Tomakokamikaze** [comment]
Also, yall should check Imperialis Auxilia too, pretty sure things are old AF there

**Comment by Mayegelt** [comment]
> @Mayegelt I will check it, but before you close, you might wanna check the LoW entries, I’m pretty sure things there are outdated. Also, are Rapiers relentless? Can they move and shoot heavy weapons without issue?

I think the LoW should be ok, because I updated them a short time ago. As a load got moved into GST. But if you find issues let me know.

The rapiers are artillery, so should have all rules associated with that. But I might need to add it. So will look again when I have some free time.

If you can compile a list of errors for Militia, it will make it easier for me to sweep through fixes. If not I'll try to dedicate some time to when I can.

**Comment by Tomakokamikaze** [comment]
@Mayegelt 
Household retinue Squad -> When choosing to exchange volkite chargers to Power Axes, sargeant not switching with the unit

Dracosan -> You can now have the twin linked lascannon and the Demolisher Cannon at the same time, please fix

Auxilia Primaris-Lightning Strike Fighter -> Agile rule not saying what it does
-> Missile Barrage Rule not sayign what it does

**Comment by Mayegelt** [comment]
Household Ret: Fixed that one. There was some mislinked hide functions that seemed to be linking to somewhere different entirely. So now should be working fine.

Fixed both issues. Forgot to add a Max 1 on the Las / Demo cannon bit. Also moved extra armour where it should be with a min 1.

Missile Barrage was a bit of a pain to find. Turns out it is back from Book 2, and never repeated. Though i think if i'm not mistaken, it is a relic of a bygone age. And the rule no longer means anything as there isn't a limit on the number of missiles you can fire anymore it seems, outside of the max amount of things you can fire at full BS vs snap shooting the rest.

Added additional rules for Strafing Run and Tank hunters as appropriate.

Fixed Aurox armour. Some of these things seem to randomly happen when uploading, it seems to change or erase some data entries, though this might have just been input wrong at the time.

Stormhammer. Multilasers now added. Hull-Mounted Lascannon added. Not sure why you had an extra heavy flamer.

Has bought up something for me though with one of those things...
The vehicle may exchange any of its multi-lasers for one of the following options: Heavy Bolter, Heavy Flamer or Lascannon (+10pts)
If you bought the Pintle-mounted Multi-laser or Heavy Flamer. Taking the Multi-Laser option. Can that then be swapped for the above options... So actually you could buy a Pintle-mounted Heavy Bolter, Heavy Flamer, Lascannon (+10pts) or Multi-laser.
Didn't add that into the file as not sure about it.

Legion Moritat thing is a good catch as well. Hadn't noticed that one. Basically Compulsory HQ option hadn't been added to Legion Allies roster type for some reason. Or maybe was but disappeared for some reason.

Keep up the good work finding issues @Tomakokamikaze. As i said many times before. I can't fix what I don't know is broken. A lot of the Mournival stuff was added as I had spare time and nothing to distract myself. ATM its stalled a bit, right near completion of the LA stuff. But it will be worked on again. But I will always prioritise official stuff over the other bits.

**Comment by Tomakokamikaze** [comment]
@Mayegelt for the pintle multilaser, I think RAW yes, as it says ANY OF ITS MULTILASERS but rules as intended, no, I dont think I have ever seen a pintle Las Cannon
Hehehhe
