### ISSUE TITLE
Solar Auxilia, Imperialis Auxilia and Legiones Astartes small fixes

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1743]
Hello there folks, it's me again, with a new list of complaints

firstly, krak Granade (Assault) profile missing in too many places to count. kinda useless cuz we all know by now, but still.

what we missed in Solar Auxilia?

This rule, this also applies to Marine Breacher squads and Marine Destroyer squads: note that its all saves according to the CIAL pg 19, thats quite a boost!
![image](https://user-images.githubusercontent.com/21247755/90297516-24484280-de65-11ea-817e-8aa6447ea657.png)
and thats different from the marines rule
![image](https://user-images.githubusercontent.com/21247755/90304320-d9dabc00-de8c-11ea-9343-2c15edf73703.png)

Veletaris Storm Sections not coming with Volkite Chargers pre chosen

Imperialis Auxilia (AKA) Imperial Army:

-The Muster of Worlds stat changes not automatic (maybe its asking too much)
-Frenzon Dispensers - Rage rule nto listed
-AUXILIA GORGON HEAVY TRANSPORTER - no transport capacity
-AUXILIA MALCADOR HEAVY TANK - missing fast rule (wich should be removed when siege armor is chosen)

Ebon Keshig should not count as compulsory elite for ZM attacker

Nostraman Chainglaive says Strengh = 1 (I think you mean +1)
also Nostraman Chainglaive not showing for destroyers sargeant

Legion Outrider showing that ANY marine may exchange his ccw for a power weapon

I think that's it for now

Also, considering the 2 missing Legions, you can play as them using the following rules from (LAAoDAL pg 122)
![image](https://user-images.githubusercontent.com/21247755/90304244-270a5e00-de8c-11ea-981f-479bac43f9e4.png)
may I suggest the creation of 2 new entries in Legion and Allegiance?
I would suggest 
II: Legiones Astartes (Sttuborn)
XI: Legiones Astartes (Furious Charge)

**Comment by Mayegelt** [comment]
Krak Grenade: Assault profile added.

Void Armour: Really odd one. Basically the rules are circular. Void Armour counts as Hardened armour, which gets the same rule as Reinforced Void Armour, which gains all the benefits of Void Armour... The reroll is worded slightly differently on each, but is identical in effect as its just vs templates and blasts. I think the old Hardened armour was just reroll 1s.

Veletaris: default weapon sorted

Muster of Worlds. Warrior Elite, Genecrafted, Survivors of Dark Age, Feral Warriors, Blade and Fury & Abhuman Helots
Frenzon added Rage rule.
Gorgon: Fixed transport part.
Malcador: Fixed lack of Fast Rule

Nostraman Chainglaive: Corrected Strength (again)
Destroyer Sergeant: Fixed issue that they weren't being flagged as a character. This was preventing some weapon selections.

Outriders: Fixed issue for Power Weapons.

The "Unlisted Legions" entry was based on prebook 7, when legions were not all given rules (Spacewolves and Thousand Sons being the last, due to Book 6 giving temp rules for Whitescars, Dark Angels and Blood Angels).
