### ISSUE TITLE
Rift Barb - wrong points for troops?

### ISSUE THREAD

**Issue by DamonRafael** [BSData/horus-heresy#1826]
Hey there,
It looks like the points for Rift Barb are wrong.
Regardless the number of model in a unit, it remains '3'.
In the rules it says:
"Bear in mind that every model in a unit of Daemons of the Ruinstorm must have the same Emanations of Horror, and so if an Emanation is bought for one model in a unit, it must be bought for all of them."
Therefore, if I have 5/10/20 models the barb should cost - for that troop - 15/30/60 points (still just a model being able to shot with it).

Am I wrong? And if yes, why?

Thank you.

**Comment by Mayegelt** [comment]
This old chestnut :D
Basically it is entirely unique that it is just listed as "(3/10/15 points):" whilst all other entries have "(3/10/15 points per model in the unit):"
So you are only paying a singular cost for the whole unit to get the buff. However as it says in its rules it also has the limitation of only 1 model in the unit can ever actually use a rift barb. Other ones like Corrosive Vomit and Flaming Ichor have a 1 in X can use, and Spine Volley and Bone Shards allow all of the models to use.
People have argued that it is a misprint, or otherwise Warp Scions would be listed the same (as only one of them can use). However no correction has currently been issued. So it is currently the points it is.

![image](https://user-images.githubusercontent.com/20280410/98850302-78ef5f80-244c-11eb-82b1-78f113e7377c.png)

**Comment by DamonRafael** [comment]
Thanks for the fast answer.
I got what you mean, but I personally think that's a rule bending tryhard :-\ 
It clearly states in the beginning that **all** model in the units **must** take the same upgrade, and it also says that you can actually choose which model is shooting with a particular wapon. 
If you only pay once for the barb, than you are giving the weapon to a specific model, which you must clearly identify and goes against the 'overall' rule. 
 
I personally think this is a misprint, as you said, and I think we should go a bit forward and use the rule as intended and not as written :-)

**Comment by Mayegelt** [comment]
I could add a box for something like that.

As to the "It clearly states in the beginning that all model in the units must take the same upgrade" in essence as written they do. It's just the cost is singular for the unit, rather than multiplicative. So for the 1 cost the whole unit is upgraded, so every model has it.
That particular rule is more likely to have been put in so that you don't have things like Brass Collars or Warp-scaled Hide on 4-5 daemons in a unit to soak a bit of damage and have the rest without. Or same with shroud or quicksilver for their buffs. Or a couple of sundering fangs to act as tank punchers.

**Comment by DamonRafael** [comment]
I think there are two points here.
First, they say:
- Every model in a unit of Daemons of the Ruinstorm must have the same Emanations of Horror
So here they state what you say: you can't give warp-scaled hide on 4 models in a unit of 20. Correct!

Then they say:
- if an Emanation is bought for one model ina unit, it must be bought for all of them.
So here I read: if you buy an upgrade for a model,  you have to buy the same for the whole unit.
Meaning that, if you buy a barb for a model (which is: a lesser daemon in a troop of 20), then you have to buy it for the rest of the unit. 
Also, all emanations' points are expressed on a per model base, it seems really hard to think that the barb isn't.

Makes little sense, but even 1d4 chan intended in this way
https://1d4chan.org/wiki/Warhammer_40,000/Tactics/Daemons_of_the_Ruinstorm_(30k)
![image](https://user-images.githubusercontent.com/38949231/98928363-0036e480-24da-11eb-8423-8e4b8ea74c4b.png)

Now, I play demons ofc, so it would be great for me to just pay 3 points for a unit of 3 beasts and let them shoot from wherever they want.
Still I don't think that's the sense of it. :-)

Moreover, I don't think it's hard to miss the "per model in the unit" as it could be a copy paste of the column settings from the left one, where the first line (Lord of socery) doesn't have it.

But hey, happy to be wrong :-) Would be great to find a discussion about it to see how others are playing it eheh.

**Comment by Mayegelt** [comment]
If you have a lot on facebook in the "daemons of the ruinstorm - horus heresy" there was long long long winding arguments really early on about it, but once again it is a case that no one is ever going to convince the other that they are wrong (or at least its rare).

What is a great counter to "The unit types in each bracket are shown below. Please beart in mind that every model in a unit of Daemons of the Ruinstorm must have the same Emanations of Horror, and so if an Emanation is bought for one model in a unit, it must be bought for all of them." is that as written if you say that that means it is 3/10/15 per model when not listed as such currently. That would also mean that ones like "Daemonic Wings (5/25/- point per model in the unit)" if you applied the same logic would then in a unit of 5 lesser daemons cost 25pts per model. So the unit of 5 would then cost (12+25 X 5 =) 185pts rather than 85pts. That is of course "As Written" currently if you follow the same logic. Which I know is crazy.

Anyway, I've added this.

![image](https://user-images.githubusercontent.com/20280410/98929612-50f70f00-24d3-11eb-808a-e1cafc652c39.png)

**Comment by DamonRafael** [comment]
I don't get your point here:
"that would also mean that ones like "Daemonic Wings (5/25/- point per model in the unit)" if you applied the same logic would then in a unit of 5 lesser daemons cost 25pts per model. So the unit of 5 would then cost (12+25 X 5 =) 185pts rather than 85pts"
To me it is clear that in this case you pay 5 points per model (speaking of lesser daemons) as written, and not 25. Why you say so? :-| 

Anyway, thank you for the addition :-)

**Comment by Mayegelt** [comment]
The list cost is the list cost.
So either the cost listed is the unit cost, or an individual model cost.
So if it is a model cost. The cost for the emanation is listed as (* per model in the unit). So you would have to buy the emanation for the listed cost of (* X models) for each model. Making it (* X models) X models.
Rather than unit cost which is (* X Models) which if why currently as written rift barb is only 3pts or whatever. As the emanation is bought for the unit, not for the model.

**Comment by DamonRafael** [comment]
I don't get it, honestly.
From the book:

"For example: If a player wishes to add Crushing Claws to a unit of Lesser Daemons then the cost is listed as
5/15/10. As the Lesser Daemons fit in Bracket One, the cost to pay is 5 points per model."

What I'm saying is that in the description of the barb points, the indication "per model in the unit" is missing, so that it works as all the others (but the lord of sorcery, again). That should sum it up pretty easily.

**Comment by Mayegelt** [comment]
Yeah, I understood what you meant. The argument was an endless circle with a few people.
The basic of it ended with Rules As Written is the current rules. Rules As Intended is a really vague thing that doesn't hold weight, as there are probably only a handful of people who know for sure what was Intended. So the argument of it missing "per model in the unit" is RGIWNPOI "Rules Guessing Intention With No Proof Of Intent"

For instance I could guess that the cost of Power Glaives for Whitescars is intended to be 15pts, rather than 25. Because surely the intention of the pricing of the weapon should never be the same as a Paragon Blade, which is superior. Or the Blade of Perdition which is also AP2 and Two-handed and has Master-crafted, but 20pts which is also superior and from the same book. However I have no proof of Intent that it was wrongly priced.

Either way, its imported now for people who want to play with it under the RGIWNPOI for Rift Barb. Hopefully some FAQ's will come out at some point. We have only been waiting for 1 1/2years for a new one now. And some are desperately needed.
