### ISSUE TITLE
Legiones Astartes - Minor issues

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1829]
Legion Herald
demands to be warlord

Tsolmon Khan
Command Bodyguard Squad option not showing
Combi Melta should be capped at maximum 1
His rule of allied of the Silent Sisterhood is not showing

Shattered Legions
Whites Scars/Blood Angels/Night Lords/Possibly all others
Legion Unique Units should already come with Shattered Legion: (Their Legion) Pre selected

Headhunter Kill team
Headhunter sergeant should have one power dagger as default, and be able to buy an extra one for 5ps, to a maximum of 2 and minimum of one.

Sister of Silence Pursuer Cadre
Steeltalon Wing missing weapons (armor is weird too)

Auxilia Thunderbolt Heavy Fighter
Not showing any weapons

Suggestion
Rename "White Scars Kyzagan Assault Speeder" to "Kyzagan Assault Speeder, White Scars"

**Comment by Mayegelt** [comment]
Heralds have to be warlords unless you have a Primarch in the army. See Rite of Command special rule.

Tsolomon Khan: Command Squads are now generally moved to the bodyguard category, as per what MotL rule on BS says. This was done to fix some issues such as bike, jetbike and jump pack command squads. An exception is with Qin Xa who I hadn't worked out how to do it right, but think I might have just worked it out in my head for a future push.
Combi-Melta should throw up an error if you take more than one. Have made a quick fix though that should sort it.
Does have his option to take a sister of silence oblivion knight-centura listed in his options. See Piccy
![image](https://user-images.githubusercontent.com/20280410/99838719-7a620b80-2b61-11eb-9c7d-3850108e3a56.png)

Shattered Legions: Unfortunately due to the way the LA list works for adding their options, it will show them with both the shattered legions options in their rules. There is a way to fix this. However it would require a huge rewrite I think to section them all off and readd them to all units with the dependency's.

Headhunter kill teams: The whole squad comes with power daggers, he may buy an additional one, as shown here. The unit entry contains all the options they all have.
![image](https://user-images.githubusercontent.com/20280410/99839281-581cbd80-2b62-11eb-9834-981207bf1907.png)

Sister of Silence Pursuer Cadre: Steeltalons don't have any weapons or armour, only the Jackals can take weapons..

Auxilia Thunderbolt Heavy Fighter: Seems to be an issue, Added the weapons back in. Also noticed the Militia one wasn't showing as Twin-Linked.

White Scars Kyzagan Assault Speeder: I can't see it makes a big difference which way around it is called. However the unit entry is as it is currently. Though I can see that many units are tagged as "XYZ, Legion" at the end rather than "Legion XYZ". Either way if changed now, it might cause confusion to the way everyone else finds them currently.

**Comment by Tomakokamikaze** [comment]
@Mayegelt 
Headhunter prime doesn't come with power dagger as default
and when you choose the extra one it says you have 1 too many

As for Tsolmon Khan and sister of silence, its missing the rules that say that he can bring Silent Sisters without suffering Ld debuff

**Comment by Mayegelt** [comment]
Headhunter prime: I was unaware of the issue if you select his personal option that it flagged an error. I will fix that one. However his default one is there in the same way as "Frag & Krak grenades" and other such items are included in the unit entry (aka every model has 1). Not replicated again inside of the characters entry. Another example is like with jetbike sky seekers. the default entry includes equipment like bolt pistols and the jetbike and the jetbikes weapon. These things are not then also listed under the sergeant entry.

Tsolmon Khan: as I put in my edit. It seems for some reason, some people were getting the rules, others were not. Not sure why. I have readded the rules to him, so now it should be there for all.

**Comment by Tomakokamikaze** [comment]
yes, but Headhunter Prime can exchange his power dagger for stuff, there is where I think the problem lies

**Comment by Mayegelt** [comment]
Ahh kk. I think I've now seen the issue. Sorry, not well ATM and finding it hard to work out some things as issues.

Anyway, required a small rewrite. Now its fixed. You will have to select it from the "May exchange Power Dagger for:" option for his original one. The other is able to be taken from "May Take"
In the case of Mournival the option for "May exhange..." is now a new selection of "May take" as they do not give up their power dagger, but instead the power dagger that they "May Take" becomes taken by default at 0 cost (as the Mournival rules do not allow you to take 2..
