### ISSUE TITLE
DA units and price (Mournival Rules)

### ISSUE THREAD

**Issue by Metaliptica** [BSData/horus-heresy#1842]
With the latest FAQ, DA Companions with terminator armor don't appear anywhere in the Lion's Entry or when a praetor in terminator armor is selected.
Also when using the Dreadwing RoW, is it possible to add the phosphex and rad grenade option for independant character for +10 points ?

Thanks for the efforts you put into this.

**Comment by Mayegelt** [comment]
Hi ya @Metaliptica .
To the first point reguarding the DA Companions. They are now located in the bodyguard section and as you pointed out it requires the praetor to have terminator armour on. In addition, a command squad, as per the rules requires the character taking them to be the Warlord (which must be selected in battlescribe). The Lion however due to the wording of both the FAQ and the DA Companions entry is unable to actually take DA Companion bodyguard in termy armour, as it only allows a "Legion Command Squad" to be in termy armour if its a Praetor in terminator armour or a Primarch (which I do think is a bit lame).

![image](https://user-images.githubusercontent.com/20280410/103446230-20cb2180-4c75-11eb-8fbb-ae6f482e013b.png)

![image](https://user-images.githubusercontent.com/20280410/103446245-54a64700-4c75-11eb-95b2-efbf6a8ac4cd.png)

As per the Dreadwing ROW options. It gives independent characters and units with the dreadwing scion Rad and/or Stasis grenades for 30pts each, not 10pts. This is located in the legion specific options.

![image](https://user-images.githubusercontent.com/20280410/103446307-02b1f100-4c76-11eb-9567-ca4f5d832cd6.png)

If you are talking about changes from the Mournival events guys. I need to get back onto them, as they haven't been updated since 3.3 on my end. Hopefully as I have the next almost 3 weeks off work, I will be able to crack on with some of the changes. Though I am still struggling to do so due to having a bleed in 1 eye that is still causing me some discomfort.

**Comment by Metaliptica** [comment]
Sorry for the lack of precision. I was indeed talking about the mournival
set of rules which allow the Lion to take Terminator Companions, equip
heavy destroyers with Plasma incinerator under the dreadwing rite and alter
the price of grenades etc ...

please take time to take care of yourself and once again: thank you for
putting time and effort into this.
