### ISSUE TITLE
No warlord trait to choose from

### ISSUE THREAD

**Issue by Tntm1ner** [BSData/horus-heresy#1879]
it says I need to choose a warlord trait but I can't find an option to choose any

**Comment by capitaladot** [comment]
Thanks for the report. Which HQ choice are you using? Could be that guy is missing a Warlord checkbox.

**Comment by Tntm1ner** [comment]
I'm using the standard pretor and he has a checkbox for warlord the problem is i need to choose a specific warlord trait and there is no option for that--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 02.02.21, 05:13 schrieb "Austin C." <notifications@github.com>:

   
  Thanks for the report. Which HQ choice are you using? Could be that guy is missing a Warlord checkbox.

**Comment by capitaladot** [comment]
They're all the way at the bottom in the desktop app.

**Comment by Tntm1ner** [comment]
The problem has been resolved after updating the data I found the warlord trait selections somewhat inconvenient to make them their own selection but there--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 02.02.21, 05:13 schrieb "Austin C." <notifications@github.com>:

   
  Thanks for the report. Which HQ choice are you using? Could be that guy is missing a Warlord checkbox.

**Comment by Mayegelt** [comment]
Sorry for the inconvenience caused.
Basically it's the list that requires it, rather than actually having to add a warlord trait.
Any new list it will automatically put the selection in.
Due to my dislike of nesting (menus in menus in menus) which makes it harder for app users to find things. It was made as a new selection. This was also done as many people will need to roll there trait, so adding it as optional to pick on there if you just wanted to check out what hey did, or maybe use the app as your list during games you can turn it on or off without producing an error.
