### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1884]
Tsolmon Khan: cant select jetbike for bodyguard when he is the warlord and is on jetbike

Primus Mediacae / Legion Champion shouldnt have the Warlord option (probably other consuls as well)

Golden keshig, Ebon Keshig, Falcon's Claws, Kyzagan not coming with Shattered Legion White Scars

**Comment by Mayegelt** [comment]
Hi @Tomakokamikaze
On my version I seem to be able to take the command squad on the jetbikes with Tsolomon Khan, but I'm working on a version unreleased. But I don't think I have changed it since the release version V623

I'm unsure what rule you are thinking of to prevent Legion Champs, Primus Mediacae or other consols from being the warlord. If it is the rule of "Support Officer", then that just prevents them from being the Compulsory HQ. But they could still be the Warlord, so long as something else would work to fill the Compulsory HQ choice. If its something else then please let me know what and where.

The Golden Keshig, Ebon Keshig... one is an odd one. Looks like I might have included the Shattered Legion box by accident on each of those things, when clearly they shouldn't have had it...
Also found that the Blood Angels units had the same issue. Clearly while speeding to release I added them by mistake. But its only taking 2.5 years or whatever to find :)

**Comment by Mayegelt** [comment]
Should go live in the next couple of hours.
