### ISSUE TITLE
Talons of the Emperor issues

### ISSUE THREAD

**Issue by Abhoras** [BSData/horus-heresy#1885]
1. Some weapon options for the custodes have wrong description
Adrathic Destructor for Saggitarum guarerd has the same weapon profile as Adrastus Bolt Caliver
Pyrihite spear weapon profile is not showing at all

2. Some options text seems to be copied directly from the book which is too long and is therefore not displayed properly (on android device)
For shield captain is displayed the following: "A single Shield Captain in your army may be upgrade..."
For sagitarum guard: "Adrastus Bolt Caliver: One memeber may replace thei..."

3. The list requires to have at least one fortification by default

**Comment by Mayegelt** [comment]
Hi @abhoras
1. The Adratic Destructor actually does have the same profile as the Adrastus Bolt Caliver's Disinteration beam. The advantage that you get by taking it as an upgrade for the Saggitarum guard is that that person also gets the Magisterium Vexilla as well.

2. Unfortunately that is a limitation of the app. However if you select the option by pressing and holding you can use the eye icon to read the full text if you don't know what the option is meant to say. Remember that battlescribe is not meant to completely replace the books, but just serve as a way to make lists. So you may have to refer back to the books from time to time.

3. Are you saying that Battlescribe is telling you that you need to have 1 fort by default (if so, I don't seem to be able to reproduce this)? or are you saying that it should be forcing a min of 1 fort buy isn't (please write a long answer to which of the options, as a "Yes" or "No" will be confusing). I can not see anywhere that they must take a fortifications, other than if you take a a Castellan or Garrision Force Org Chart.

**Comment by Abhoras** [comment]
1. Aha, thats new to me.
2. I was thinking that maybe the selection text can be shortened to: "Upgrade to Tribune" and "Replace with Adratic destructor and vexilla.
3. My bad. I mistaken Castellan with Centurion, since the second one is missing for Talons. Is there any reason for that ommision?

**Comment by Mayegelt** [comment]
@Abhoras the trouble is that because only 1 in the unit can, it needs to be put that way. Otherwise people will complain it throws up errors the other way.
I could probably sort it out with a small bit of playing around to make the item just default for everyone. But it might cause more issues for people who already have armies. Though might look a bit better.
@capitaladot what do you think? if I did it, it would slim down the unit entry a bit, and mean that you don't have to select every individual model as a new thing (like vets are, rather than like termys are in LA).

As for Centurion. I assume it was just not put in by the person who wrote it when they wrote it in. But there is no harm in doing so.
