### ISSUE TITLE
[Bug] Primaris Nullificator Paying for Armour.

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1892]
The Primaris Nullificator should not be having to pay for his Cataphractii armour. It is given as part of his consul upgrade and should not require paying for.

**Comment by Mayegelt** [comment]
Thanks for the report. The cost of the primus nullificator is including the cost of the cataphractii armour he wears.
If you notice, the consol option is listed at only 10pts, rather than the 45ts that the upgrade for the consol should be. This is to factor in the 35pts for the cata armour he must buy.

**Comment by TheRavingRaven** [comment]
that's what i get for thinking i'm clever.

**Comment by Mayegelt** [comment]
I could probably do it better by setting cost to 0 for armour and adding his true cost to him. It's a bit of a relic of the old system that didn't allow that.
