### ISSUE TITLE
Horus Heresy Book 9 Crusade. List of FAQ Changes.

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1895]
1. Add Rhino transport option for Deathwing companions.

2. Remove Land Raider Proteus option for Deathwing Companion Terminators, replace with Spartan transport option.

3. Remove Hatred and add Preferred Enemy (characters) to Firewing Enigmatus Cabal.

4. Change Dreadwing Interemptors transport parameters to "10 models or less" rather than exactly 10

5. Add "This counts as a sword for the purposes of the Mastery of The Blade" to Corswain's The Blade's item description.

6. Remove the Inbuilt option for the Lion to take Deathwing Companions. Instead give him the same check that allows for Deathwing Companions and Deathwing Companion Terminators to be taken in the "Command Squads" section.

7. Enable 4 additional non-compulsory troops choices when The Storm of War rite of war is selected.

8. Remove Independent Character units from the count that determines weather or not there are more non tactical/assault. than other units combined. 

9. Update rules text for the Storm of war to reflect changes.

**Comment by Mayegelt** [comment]
Thanks for the list. I had put a thread the other day up. But didn't quantify all the changes. So this will be useful.

**Comment by Mayegelt** [comment]
Ok putting in changes now.


- [ ] Add Rhino transport option for Deathwing companions. (Not required, they already could)

- [ ] Remove Land Raider Proteus option for Deathwing Companion Terminators, replace with Spartan transport option.

- [ ] Remove Hatred and add Preferred Enemy (characters) to Firewing Enigmatus Cabal.

- [ ] Change Dreadwing Interemptors transport parameters to "10 models or less" rather than exactly 10

- [ ] Add "This counts as a sword for the purposes of the Mastery of The Blade" to Corswain's The Blade's item description.

- [ ] Remove the Inbuilt option for the Lion to take Deathwing Companions. Instead give him the same check that allows for Deathwing Companions and Deathwing Companion Terminators to be taken in the "Command Squads" section.

- [ ] Enable 4 additional non-compulsory troops choices when The Storm of War rite of war is selected.

- [ ] Remove Independent Character units from the count that determines weather or not there are more non tactical/assault. than other units combined.

- [ ] Update rules text for the Storm of war to reflect changes.

**Comment by Mayegelt** [comment]
Should all be done now. Will post an update for testing and hopefully should be live soon.
