### ISSUE TITLE
Qin Xa Bodyguard minor errors

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1927]
his bodyguards should only have tartaros pattern, and its going up to 7 Bodyguards, should only be up to 4

**Comment by Mayegelt** [comment]
Thanks for the report.
The 7 is a mistake, I'm assuming a Mournival rule slip.
The terminator armour one is a fun one.

"If the army’s Warlord for which the Legion Command Squad has been chosen is a Praetor or special character wearing Terminator armour, or if they are a Primarch, the squad may exchange their Wargear for a set of Terminator armour. If this option is chosen then every member of the squad must be upgraded to the Terminator Bodyguard Wargear selection and has access to the following options, rather than those shown previously (the same type of Terminator armour must be chosen for the entire unit):"

What seems to have been put there from the FAQ is that if the warlord has some Termy armour the command squad is also allowed to. However it doesn't say it has to be the same pattern of Termy armour as he has. Just the same pattern for all the command squad as a unit.
In essence if they had to wear the same it would mean Abaddon couldn't have any as he has special Termy armour. I think a few other chars have same deal.

**Comment by Mayegelt** [comment]
Ok just looking at it. The max amount is a bit of rules slip. The value is max 4 but it is allowing up to 7 of them to be chosen. However it does then flag the error that you have taken to many.. The Mournival rules allow more of them to be taken. I'm not sure why the cap increase is applying to the roster builder without the activator being triggered. But as said it is giving an error on selecting to many, so can be resolved by user.
