### ISSUE TITLE
Legion Esoterist force weapon error.

### ISSUE THREAD

**Issue by Grunanca** [BSData/horus-heresy#1935]
I get a warning on legion Esoterist that atleast 1 force weapon is needed (thousands sons army), even if I buy 2 force axes.

++  Crusade (Legiones Astartes: Age of Darkness Army List) [2,640pts] ++

+ HQ [440pts] +

Esoterist [170pts]: Arcane Litanies [10pts], Artificer Armour [10pts], Cult Arcana: Raptora (Telekinesis), On Foot, Psychic Mastery Level 2 [30pts], Psyk-out Grenades [5pts], Refractor Field [10pts]
. Consul [15pts]
. . Esoterist [15pts]: Support Officer
. Power Weapon [20pts]: Force Axe [5pts]
. Power Weapon [20pts]: Force Axe [5pts]

**Comment by Mayegelt** [comment]
Ok this looks like an interface issue.
Because TS can exchange power weapons for force weapons if they have a psychic level they get the sub option on power weapons to turn them into Force weapons.
If you select the replace chainsword with the Force weapon entry (which is free) then that will work.
The only way to stop this issue would be an option that causes more problems than it solves.
