### ISSUE TITLE
Deathwing companions: Deathwing retinue has incorrect wording

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#2001]
Reported on Discord by hrobar, just adding it here.

Their correct wording is on pg165 of book 9 crusade

Correct is: Deathwing Retinue 

A Deathwing Companion Detachment may only be chosen as a retinue for a Legion Praetor with the 
Legiones Astartes (Dark Angels) or Legion special character with the Warlord and Legiones Astartes 
(Dark Angels) special rules, and may not be taken as part of an army on their own. They take up a single 
Force Organisation chart choice with that Dark Angels Praetor, and must be deployed with the Praetor 
of the Detachment for which they are bought. Once deployed, the Legion Praetor, or Legion special 
character, may not voluntarily leave the Deathwing Companion Detachment

And when taken with Lion they do not count for his LoW allowance cost (from the book 9 errata) this part is there

**Comment by zopha** [comment]
Having a look and I can see they're not part of the Retinue Share Selection Entry Group for The Lion.
![image](https://user-images.githubusercontent.com/1666415/142230474-bf100cca-5593-4023-9fed-743bde7cb800.png)

![image](https://user-images.githubusercontent.com/1666415/142230714-d7df203f-24be-497e-a52d-b70b6e1d2084.png)

They can be added but I'm not sure if this would impact the LoW allowance cost or it should be done a different way.

**Comment by Mayegelt** [comment]
You should add them though the Bodyguards tab rather than the Retinue one. The Retinue one is only used for units that will add the the LOW cost. Legion Command Squads got taken off of the LOW value, as did Perty and Dorn's vehicles. But most other units didn't.

The wording however will still be fixed next push.

Sorry about the delays, Been really ill lately, so not really getting anything done. Hopefully will soon.
