### ISSUE TITLE
Red Hand Destroyer Assault Squad

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#2014]
Some minor issues
Falax Blades on the unit are set to max 1 

Also has error "cannot have any selections of Red Hand Destroyer assault squad (hidden)"
When you have multiple detachments in the same force as shown below. Both forces are World Eaters

![Screenshot_20211215-125115](https://user-images.githubusercontent.com/8060951/146247349-88157259-3664-40f5-83ae-73b4134bc617.jpg)

**Comment by Mayegelt** [comment]
First issue is odd. I've just loaded it on my PC and its fine, and then reloaded on my phone and also working fine. But then when I reloaded again to try on my phone it didn't work. I've worked out a fix for it and will put it through now.
HOWEVER you can't have 2 Crusade detachments in the same force anyway... So that isn't an issue. You also can't ally your own legion to itself.
