### ISSUE TITLE
Cults And Militia missing Flak Missiles

### ISSUE THREAD

**Issue by ThatEvilOne** [BSData/horus-heresy#2017]
**Describe the bug**
For 5 points a piece ontop of the missile Launcher, Fire Support Squads are supposed to have access to flak missiles. the option is currently unavailable.

**To Reproduce**
1. Go to Imperialis Militia and cults army v123
2. Click on a fire support squad
3. Click "exchange heavy stubber for:"

**Comment by Mayegelt** [comment]
Will try to fix later today if I can.
Will also need to fix for AoDC as it will have same issue.

**Comment by Mayegelt** [comment]
> **Describe the bug** For 5 points a piece ontop of the missile Launcher, Fire Support Squads are supposed to have access to flak missiles. the option is currently unavailable.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Imperialis Militia and cults army v123
> 2. Click on a fire support squad
> 3. Click "exchange heavy stubber for:"
> 4. See error

Looks like there isn't an error, it is just a buried option.
![image](https://user-images.githubusercontent.com/20280410/147953356-093a137d-0448-4603-85ef-7e088cf9e1d3.png)

It could be made simpler though. What I might do is change the formatting of the unit to make the options for each model a list option like with Marine Veterans and stuff. That way it will be easier to select. Maybe even change the formatting so that there is an option for 'Missile Launcher with Frag & Krak' and a separate one 'Missile Launcher with Frag, Krak & Flakk'.
