### ISSUE TITLE
Legion Veteran Reconnaissance Squads

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#2048]
These need to be allowed as Compulsory Troops whenever Recon Squads would be, such as with the Legion Recon Company and Hunter-Killer Mission Rites of War. They also need to have the ability to select which Shattered Legion they belong to. Some Legion Weapon options are missing, such as the Phoenix Power Spear. They also need their Dedicated Transport options.

 - OS: iOS 15.3
 - BattleScribe version 2.03.15
 - Release version Mournival v48

Thanks

**Comment by Mayegelt** [comment]
From what I can see there aren't any RoW that meantion Vet Recon squads being compulsory. 
"Support Squad: The unit cannot be taken as Compulsory Troops unless using a Rite of War that allows this option."
The Cent RoW only mentions "Legion Recon Squads (or Ammitara Intercession Cabals or Falcon’s Claws) must be taken as Compulsory Troops."
As for the Shattered Legion stuff. I don't think I've added it to anything, as the Shattered Legion rules thing just doesn't seem to work anyway. It needs an entire rewrite as the selection options given there on any unit don't actually make any usable difference to them. This is in part due to the way all legion rules are given out.
I can also see the Phoenix Spear for the sergeant when Emps children legion is selected. So not really sure what is messing up on iOS...

**Comment by LachrimallusExterminator** [comment]
![1D122A6F-6145-42B8-A509-ABAB310D62EB](https://user-images.githubusercontent.com/84422145/160273818-1a067d5c-d429-404b-8a0e-5f3d89909bef.png)
![BF1B60D2-AA3B-4A3F-86A9-0B0E96C0D78F](https://user-images.githubusercontent.com/84422145/160273844-c670ecf9-cf04-4407-aa42-207215843243.png)

**Comment by LachrimallusExterminator** [comment]
See the images above

**Comment by Mayegelt** [comment]
Will get to it. Just unwell again

**Comment by Mayegelt** [comment]
Should be in next push soon.
