### ISSUE TITLE
Iron Warrior Warlord Traits in Word Bearer List

### ISSUE THREAD

**Issue by donthaill** [BSData/horus-heresy#2192]
**Describe the bug**
When selecting a Praetor as the Warlord, in a Word Bearer legion list, the IV: Iron Warriors Warlord Trait list appears.

**To Reproduce**
1. Create Crusade Force Organisation Chart list
2. Select XVII: Word Bearers as the Legion
3. Add Praetor as an HQ option
4. Check "Warlord" checkbox in parent Praetor line (can also select "Warlord" in child line to create issue)
5. Warlord Traits section will appear in parent Praetor line and will list IV: Iron Warriors warlord traits

**Expected behavior**
Selecting an HQ as a Warlord should display the XVII: Word Bearers Warlord Traits when building a Word Bearer list.

**Screenshots**
![image](https://user-images.githubusercontent.com/111011823/183996075-ed01fc0e-5c20-4d20-8f87-c86331e4a5a9.png)

**Device and data (please complete the following information):**
 - OS: [Windows 10]
 - BattleScribe version [2.03.21]
 - Release version [v16.0.12]

**Additional context**

**Comment by Mayegelt** [comment]
This is already being fixed I believe in next release push.

**Comment by UrsinePatriarch** [comment]
![image](https://user-images.githubusercontent.com/46959832/184003811-6be19fc4-c699-4fe7-9571-7f226577f2a9.png)
Cannot replicate issue as presented; it's very likely the submitter has not updated their data since this is not a change that I've actively made in this week's commits.

That being said, if this persists, please update your data while deleting old data as this is very likely a fringe case; if it persists even after having done that and after today's later push, I will look further into it.
