### ISSUE TITLE
Bug: Legiones Astartes requirements must operate on Force, not Roster.

### ISSUE THREAD

**Issue by fedratsailor** [BSData/horus-heresy#229]
So this is one really weird issue.  I made a roster with 2 different LACAL lists in the same force.
I used Salamanders and Iron Hands legions for the 2 different lists.
For some reason while working on the Iron Hands section of the army, Salamander options were available on the Praetor.  I.E. The iron hands praetor could take a dragonscale storm shield and mantle of the elder drake.  He could also take a firedrake terminator squad as a bodyguard.  Also the same praetor for some reason only had to pay 5pts for mastercrafting a weapon when it should be 15pts.
Salamanders Praetor was able to take a cyber-familiar and the Iron Father upgrade.

Dunno how serious this is but its something someone who doesn't own a book just building a random army might not know and take options not allowed.

**Comment by Millicant** [comment]
I know exactly what this is.  

Short version - the advent of distinguishing between "force" and "roster" came about late into the creation of this catalogue.  Some work correctly, while some still allow item/selections if the Roster (rather than force) contains the correct Legion Astartes.  

I'll fix it!

**Comment by Millicant** [comment]
Okay, this is going to take me a bit.  Turns out I (stupidly) used "roster" instead of "force" for every. single. modifier.  

So, I have to go through every entry in the catalogue and fix this.  :(  It may take me a bit, but THANK YOU for bringing it up - I will make sure it gets fixed over the next couple days.
