### ISSUE TITLE
HH2 Legion Centurion Mortifactor's Dreadnought Talon allows multiple dreadnought

### ISSUE THREAD

**Issue by Camyron** [BSData/horus-heresy#2369]
The Legion Mortifactor Consul allows you to take an additional Legion Contemptor Dreadnought Talon with a single model as part of the Force Organisation choice of the consul (Re: Keeper of the Dead special rule). However, Battlescribe only shows an error for too many dreadnoughts when more than 3 dreadnoughts are added to the talon as if it were a standard Contemptor Dreadnought Talon.

1. Create an army list for any space marine legion
2. Add a Centurion, change its Legiones Consularis option to Mortifactor
3. Add a contemptor Dreadnought Talon, add 1, 2, 3, then 4 dreadnoughts to it.
4. At 4 dreadnoughts, the Talon gets the "Contemptor Dreadnought talon has 1 too many selections of Contemptor Dreadnought (maximum 3)" error.

It would be beneficial if this was somehow changed to throw an error when more than 1 dreadnought was added, without impacting the normal Contemptor Dreadnought Talon Elite option that it uses. Alternatively it could add a single Contemptor model to the unit, as the contemptor drop pod is unusable with the Mortifactor & there's nothing else useful provided by being a Talon.

 - OS: Windows
 - BattleScribe v2.03.21.166
 - Horus Heresy v16.1.6

**Comment by UrsinePatriarch** [comment]
Fixed in next release; I had constraints in place for it, but they weren't working properly, so I've completely reformatted the unit to force singularity now.

Unfortunately, there was no easy way to do this; while your comments are helpful, the infrastructure of the data made making a singular Dreadnought outside of the Talon rather clunky, which is why I was trying to avoid doing so.
