### ISSUE TITLE
Alpha Legion Power Daggers

### ISSUE THREAD

**Issue by FinnyD73** [BSData/horus-heresy#2507]
Alpha Legion Praetors and Centurions, as well as unit leaders for Headhuter Kill teams and Lernaen Terminator units, don't have the option to take power daggers.

Also, tac squad sergeant's, recon sergeant's etc have the option to take toxin bombs, which they shouldn't have

**Comment by UrsinePatriarch** [comment]
Are you saying that Alpha Legion Tac Sgts have Toxin Bombs (which is illegal) or that they're not supposed to have them at all?

**Comment by FinnyD73** [comment]
There's a checkbox for toxin bombs, but Alpha Legion do not have ANY access
to that warhead. It just shouldn't be possible to give it to them

**Comment by UrsinePatriarch** [comment]
Okay, so the Alpha Legion guys have them, which is indeed incorrect; thank you for clarifying.

**Comment by Mayegelt** [comment]
This requires a rework of something. Either we will need to change all the "Hidden" modifiers to unhide if equal to 1 of LX in force and 0 of AL in force (or reverse if unhidden to hide.
Otherwise RoT could be reworked to have its own list of legions, and then the individual equipment could just be flagged as hidden to false in the SE by default.

**Comment by DasEi02** [comment]
So for me my HQs have access to the wargear for the Legion I select for my RoT but not to the AL specific wargear
