### ISSUE TITLE
Standard Space Wolves Inf Missing from ‘Veiw’

### ISSUE THREAD

**Issue by Stubram** [BSData/horus-heresy#2525]
If you go into ‘view’ to see a Grey Stalker or Slayer unit’s stats and rules, it only has stats for the Huscarl of the squad

**Comment by Mayegelt** [comment]
This is an issue with whoever coded it. They forgot that putting a profile into a selection entry group doesn't show it. It needs to be in a selection entry that is picked.
I have moved the profile to shared profiles and entry linked in all the selection entries to fix.
@UrsinePatriarch @alphalas @nstephenh I'm sure there are going to be a ton of these out there...

Anyway, fixed in my version now that will be uploaded and go out on the next release.
