### ISSUE TITLE
Emperor's Children - Palatine Blades, Pheonix Terminator & Phoenix Warden errors.

### ISSUE THREAD

**Issue by chronocobra** [BSData/horus-heresy#2546]
Palatine Blades (Both Units) can't select individual weapons for each member, they should be able to (this was implemented fine a few weeks ago but has since broke so not sure what happened there).

Phoenix Termies can't take a Surgical Augment for the whole unit, they should be able to at the same points as Palatine's SAs (25pts for unit).

Pheonix Warden can be selected by all 3 Centurion types, should only be selectable by Tartaros.

**Comment by Mayegelt** [comment]
I think i've fixed Pheonix Warden can be selected by all 3 Centurion types, should only be selectable by Tartaros.

Still need to do
Palatine Blades (Both Units) can't select individual weapons for each member, they should be able to (this was implemented fine a few weeks ago but has since broke so not sure what happened there).
&
Phoenix Termies can't take a Surgical Augment for the whole unit, they should be able to at the same points as Palatine's SAs (25pts for unit).
