### ISSUE TITLE
Expanded army list option

### ISSUE THREAD

**Issue by Caprera** [BSData/horus-heresy#2599]
Expanded army list options is not available to allies. 
It's not possible to add it manually as it's not even in the list.

1. Create new army
2. add main force
3. add allied force
4. once in the main window only the main force can add/use that units types. 

Would be nice to have it available at least manually.

 - OS: [Win]
 - Release version [v16.3.0]

**Comment by alphalas** [comment]
As of right now, this is likely to not happen due to limitations of the program itself.

**Comment by Mayegelt** [comment]
Could you tell me which one you are looking for that isn't appearing?
The limitations on expanded units are roster wide (rather than force). So if for instance you have a SW Vrusade FoC and add EC Allied Detachment. It gives you the options to take units like Palatine Aquilae.

So it won't work by itself, but does for compete lists made in 1 roster.
![Screenshot_2022-11-14-18-16-17-494_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/201735740-b7ebd16d-dc44-4609-a1d4-96d16dc3246f.jpg)
![Screenshot_2022-11-14-18-16-20-197_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/201735753-c6a741ea-2fd0-43ec-b854-44f1eb2cfb4f.jpg)
