### ISSUE TITLE
EC Loyalist access to Surgical Augments

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2743]
**Describe the bug**
Loyalist Palatine Blade Aquilae, Palatine Blade and Phoenix Terminator Squad have access to Surgical Augments - they should not, as these requires being Traitor.
I know that these units have option to take them as squad option, but they still require being Traitor.

Used v16.5.1 version.

**Comment by Mayegelt** [comment]
Surgical augments are not traitor only.
Only the option to take them on characters at 20pts is.

![IMG_20230301_082519](https://user-images.githubusercontent.com/20280410/222084653-b8300b82-23e2-4c26-8a17-4e5f1fb87559.jpg)

**Comment by Cylindryk** [comment]
I can  see why this interpretation, but please visit #rules-discussion and #III-emprerors-children on HH Discord.
I would still say this is Traitor Only.

**Comment by Mayegelt** [comment]
RAW says otherwise.
If it was the case that the palatines/phoenix termy were not able to take the augments, then they would likely have a * or something that says that it is traitor only on the profile. Or be traitor only units.
If an official FAQ comes out saying otherwise then I'll remove it.

Lorewise the introduction of the surgical augments to Emperors Children happens in the Novel "Fulgrim" soon after "The Cleansing of Laeran" at 000.M31. While the "Battle of Isstvan III" happens at 005.M31 (so 4-5 years later). So it is not completely inconceivable that some of those experimented on sided with the loyalists.
