### ISSUE TITLE
Some weapons missing descriptions for their special rules

### ISSUE THREAD

**Issue by krobb001** [BSData/horus-heresy#2746]
**Describe the bug**
- Sanguinius is missing descriptions for all of his weapons' special rules - `Infernus`, `The Blade Encarmine`, and `The Spear of Telesto and Moonsilver Blade`

- Judicar Aster Crohne is missing rules for his `Sapihan shard-axe`

**To Reproduce**
1. Create a new roster
2. Add the unit mentioned above
3. View their roster entry
4. See some rules are missing

**Expected behavior**
The descriptions for those special rules (Armourbane, One Shot, Rage (2), etc.) should be included 

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version: v2.03.25.338
 - Release version: v16.5.1

**Additional context**
N/A

**Comment by Mayegelt** [comment]
Ok fixed this one, will be in the next release. Also seemed like Raldoron also had the same issue. And the Talons of Perdition on the incendius also missed brutal and shred. Which i think people were reporting, but were saying it was missing its profiles, rather than saying it was missing its linked rules.

**Comment by krobb001** [comment]
One other thing I just found - Apothecary / Apothecarion Detachment are missing the Feel No Pain (5+) special rule description
