### ISSUE TITLE
Emporer's Children Apothecaries can't buy augments as a squad

### ISSUE THREAD

**Issue by Posh-Tim** [BSData/horus-heresy#2782]
When taking the Emperors Children Rite of War IIIrd Company Elite, Apothecaries aren't granted the ability to buy surgical augments as a squad. Nor are they flagged as a validation error for being a character without one in the force.

**Comment by Mayegelt** [comment]
Hi ya. Thanks for the report.
This one is one of those murky ones as both Apothecary and Tech Marines are both units and not units at the same time. The 3rd company thing also has a restriction that it's only infantry units, which in the case of the Apoth and Tech Marines could in essence be a mixed unit of some infantry and some cavalry (if some are on bikes or jetbikes).

I do not believe the intention is that for a 1 off payment of 30pts you could give up to 8 units sonic shriekers (which would be cheesy as hell).
I ended up asking on the EC Facebook group and they agreed.

So this is one I could put in, and I can do the mandatory must take part of it. But I think the equip the whole unit thing might remain off unless I can be convinced otherwise.

**Comment by Mayegelt** [comment]
Personally I think I should probably remove it from the solar medicae section. I think I probably put it in on autopilot.
