### ISSUE TITLE
Move unit upgrades from model to unit level

### ISSUE THREAD

**Issue by brekiy** [BSData/horus-heresy#2824]
**Is your feature request related to a problem? Please describe.**
Some unit upgrades are added at the model level whereas others are added at the unit level. When adding multiple upgrades, like vexillas and augury scanners, it forces the user to add multiple new models and set the upgrades individually.

**Describe the solution you'd like**
The intent is to change all occurrences of the first image to the second. Happy to take this on as a self-assigned task.
![asfsdgsdg](https://user-images.githubusercontent.com/13171432/236641620-70f2faa4-4271-4d82-b7f2-0a71167874ee.png)
![sdgsdg](https://user-images.githubusercontent.com/13171432/236641621-74f0d993-32b2-40bd-9782-5fd155b5a520.png)

**Comment by Mayegelt** [comment]
I personally preffered it the old way with the stuff being 1 level up like Vets.
Several of the other devs wanted it done so that you had to select individually. This is because for Tournament and Listmaking accuracy, you actually need to declare who has what items.
ATM its a bit of a mixed bag, and not the ideal solution. But TBH it is technically better to have it the way of the 1st pic for clarity, even if it does make it more of an arse to actually make lists and the output looks messier IMOO.

**Comment by brekiy** [comment]
Well that's unfortunate. If the intent going forward is to put upgrades at the model level then this issue can be closed.

**Comment by Mayegelt** [comment]
It was a job that was started but not completed unfortunately. So there is a mix of units with or without the new formatting.
