### ISSUE TITLE
Pursuer Cadre beasts 

### ISSUE THREAD

**Issue by LivingDynamode** [BSData/horus-heresy#2888]
Pursuer cadres, a unit in sisters of silence, are a unit that includes both sisters of silence and some monsters they take into battle. Rules as written, every model in the unit can replace their close combat weapons with an execution blade. While the sisters are given this ability in battlescribe, the monsters are not - even though they have close combat weapons, and thus can replace them with execution blades

**Comment by Mayegelt** [comment]
You have just won a small portion of the internet.
This is as you said correct. It will hopefully be put in next patch. I guess the execution blades they take are cybernetic upgrades rather than blades. Though it might be like SIF from Darksouls

![images (1)](https://github.com/BSData/horus-heresy/assets/20280410/e1130249-8da0-4a22-bdec-7a04c1aca67b)

**Comment by LivingDynamode** [comment]
Hah, yes, I was actually wanting to model it like sif and her greatsword :)
Though when doing cyber caimans I will probably make them Kroxigors
instead, because I love those guys and having big smashdown crocs sounds fun
