### ISSUE TITLE
Lords of War as a separate detachment

### ISSUE THREAD

**Issue by Kusevak** [BSData/horus-heresy#2894]
In Horus Heresy 2.0 Lords of War are treated similarly to Allied Detachments; they are added to an army through a separate Detachment and does not have to be of the same Faction as the Primary Detachment. Yet in BattleScribe Lords of War are currently selected as part of the Primary Detachment. This method is limiting as it only includes some options for selecting LoW choices from army lists outside of your Primary faction, but not from the full range that should be available.

A good solution to my mind would be to change it so that Lords of War are added through their own, separate Detachment, similarly to an Allied Detachment, so that you pick a Faction for that Detachment upon creating it and have all the options available to you.

**Comment by Mayegelt** [comment]
This one needs to be done at some point, but it requires a lot of work to solve as a new catalogue needs to be done. All the units need to be put into it, and then have a link to all the weapons, rules, legion specific stuff, as well as some RoW or whatever can affect if you can use them, or might give additional options to them.

**Comment by Mayegelt** [comment]
So I have made a pull request which "should" work to do this. It might not be the final version, as i might actually move the LoW into the file itself, rather than leave them inside of their armies, as it requires a whole bunch of catalogue links the way it is now. Which I don't know how it will affect performance.

https://github.com/BSData/horus-heresy/tree/Lords-of-War-Overhaul

You can test this by downloading the files in the link above and testing if they work for you.

**Comment by Mayegelt** [comment]
Had a rework and thing there is a better version now. Going to post it up soon.
