### ISSUE TITLE
Tsolmon Khan and knight centura

### ISSUE THREAD

**Issue by LivingDynamode** [BSData/horus-heresy#2904]
"Ally of the Silent Order: A Detachment that includes Tsolmon Khan may include a single Knight Centura as a non-Compulsory HQ choice without taking up a Force Organisation slot" means that the knight centura in question is not counted as part of the 3 hq limit and thus you could have her and 3 other hqs, but battlescribe does count them towards the limit regardless right now. I believe this is not the only example in the app but it's the only one I'm aware of right now

**Comment by Mayegelt** [comment]
Additionally it seems to be allowing more than 1 knight Centura in the army. Rather than max 1 in force.
So needs a max 1 in force, and s modifier to FoCs to give +1 max if they are in the force (can't be done like retinues are due to the wording meaning they aren't the same unit, as that has implications on stuff like ZM)
