### ISSUE TITLE
[Question] Sources for data?

### ISSUE THREAD

**Issue by Goldobsidian** [BSData/horus-heresy#296]
Hello, Im sorry if this has been asked or is available anywhere but iv spent a good hour trying to find sources for alot of the information provided in the horus heresy data files for any kind of source and Iv searched all over the internet and the only thing I keep finding is a 3rd party book by the name of Warhammer 30k, Battles in the age of heresy V2.5 by fly lords of terra. which has units that you dont such as Adeptus Custodes Honor Guard as a HQ unit but doesnt list any of the ones you have such as Legion Centerion. Where can i find the books/sources for the information or is it all just manufactured/home brew?

**Comment by Polnor** [comment]
Hello! It's from Forge World Horus Heresy series, the latest is https://www.forgeworld.co.uk/en-IT/The-Horus-Heresy-Book-Six-Retribution

**Comment by capitaladot** [comment]
Seriously? GO to the Forge World website. Buy their pretty books.

**Comment by Goldobsidian** [comment]
@Capitaladot Thanks for your outstandingly wounderful personality and response.... you know sometimes some of the most obvious things pass by some people, For example I knew forgeworld existed, I knew they had models for the horus heresy style and setting, but I, in my numerious times looking on that website and even buying from them, never came across the books Polnor pointed me to by some sheer fucking act of fate. Next time instead of being an asshole, expecially to some one who has never given you a problem in the past, be kind, generous, and not condescending and maybe youll have less headackes, drama, and more friends in your life.

**Comment by Goldobsidian** [comment]
@Polnor thank you for your prompt responce. I dont know how I ever missed those books before this.

**Comment by capitaladot** [comment]
The most rudimentary of Google searches (e.g. "horus heresy rule books") produces scores of relevant hits.

**Comment by Millicant** [comment]
@Goldobsidian welcome to the Horus Heresy and please accept my apologies for any rudeness directed your way.  I'll also suggest joining the fine group over at the bolter and chainsword you can find a lot of information and scores of Heresy-loving fanatics.  find a lot of information and scores of Heresy-loving fanatics.  

http://www.bolterandchainsword.com/forum/35-the-horus-heresy/

@capitaladot Check your attitude and consider yourself warned.

**Comment by Goldobsidian** [comment]
@Millicant, Thank you for the apology and the invitation how ever when i attempt to registure it says that the administrator is not accepting registrations at this time, or something along those lines. To be honest I was looking for the rulebooks used because the battlescribe data files are often missing pieces of information, specifically when it comes to special abilities, orders, warlord traits and so on. Horus Heresy is something Im just beganing to explore but so far I am liking what I see.

**Comment by Millicant** [comment]
@Goldobsidian Well then, my system is working!  I intentionally left many of the rules out so that people could not use these catalogues to replace the Forgeworld source books.  

Welcome to the Heresy.  Please do try again at the Bolter and Chainsword - it's a solid community.  I'm glad that my catalogues are helping you get started.  As always - please come back here to let my know of any issues or errors that you end up finding.

**Comment by Goldobsidian** [comment]
@Millicant I didnt think about it till you said it but that makes a lot of sense expecially to avoid any prosicution or threats from GW given how sue happy they have been. Ill keep trying at B&C but still locked down when I tried it just before typing this.

I will how ever state something reguarding your system, I dont mean this to be agressive, hurtful or anything along those lines so I hope you dont take it as such, its just my opinion. In the local community that I play with, alot of us use battlescribe to build the armies and use it for a quick refernce of their stats and the like. My friends and I play online togeather with the help of a program known as vassel if you know it. If I played only online with vassel and friends, having all the rules in the program would be a significant help, because spending 500 USD on source books and codex's to play a online platiform which is entirely fan made and free, kinda sucks and turns people away from the community, expecially since GW hasnt or is dead set against ever digitalizing the table top game in its full extent.

**Comment by cowomo404** [comment]
@Goldobsidian if you send an email to B&C admin with the information needed for creating an account I'm sure they will be happy to set up an account for you. B&C turned off the sign up form because they were receiving a large amount of spam, and until they devise adequate protection they are handling new users manually.

**Comment by Millicant** [comment]
I'm sorry @Goldobsidian but I can't countenance supporting piracy, no matter how convenient it is for you.  Just because Vassal is free (I'm familiar) doesn't mean that the ruleset is also free.  I highly recommend Forgeworld's books, not only because of this conversation but also because they are very high quality and worth reading.

**Comment by amis92** [comment]
I see there has been quite a discussion here. For all interested parties:

Vassal is a good project. However the actual tabletop game is un-digitalizable. The best and closest video game you can get is Dawn of War. Turn-based strategy games of 40k size would be incredibly boring and complicated. Vassal comes close - it's a "good-enough" alternative for people wanting to try things out - but take a look at the pure amount of possibilities a player has in every moment.

I also cannot agree that spending money to play free game is a good simplification. It's very misleading, indeed. The vassal pack is a copy-over of GW's IP-protected game. And only because it's free it can defend itself at all.

Overall, as much as we try to make our own lives easier, there is some common sense required.

**Comment by cowomo404** [comment]
@Millicant @capitaladot this thread got me thinking - how much of the infrastructure is already in place for the games rules in the work the team has done? Is it structured in a way that stat rules are independent from list building rules?  I have all of the HH books and 40k books - I've been keen to enter all of the rules for my own personal use just to make build an army and playing easier to manage (not for sharing) e.g. build a list - print out the sheets and go everything you need is there including all of the effects and USR. The only issue I could see if any updates/changes to the Battlescribe files overwriting anything a person might enter for personal ease of use.... thoughts?

**Comment by capitaladot** [comment]
@cowomo404: I'll go on record in favor of full text. I am a happy purchaser of Forge World and GW books, and see no need to selectively exclude things. I think doing so just encourages list making mistakes, as we partially depend on Battlescribe.

Short answer: I'd merge such pull-requests.

**Comment by Millicant** [comment]
@cowomo404 @capitaladot Unfortunately we must fall short of full text.  We will be moving much closer to it and including all weapons profiles, but some bigger-picture items like Legion-specific traits or full details for Rites of War will be left out.  

I'm aware that this may be inconvenient.  However, I feel that this is a necessary precaution to ensure that we do not tread further along an already dangerous path.  We, as owners of the various Forgeworld books associated with the Horus Heresy series, may treat this as a mere convenience.  If we include full text, we have just seen firsthand in this discussion that the lists could be used without the books at all.  If you'd like to keep a copy with full text for yourself, that is fine.  I cannot support publishing transcripts from the books as a part of this repository.
