### ISSUE TITLE
Rosters containing multiple detachments and a lord of war not opening

### ISSUE THREAD

**Issue by sir-shy** [BSData/horus-heresy#2961]
Describe the bug
Rosters which had a lord of war option and allied detachment before the update now crash battlescribe when I try to open them

To Reproduce
Open an applicable roster

Device and data (please complete the following information):

OS: PC
App being used to create lists: Battlescribe
App version: 2.03.21
Data release version: v17.3.1

**Comment by Mayegelt** [comment]
Unfortunately this is because of a change in how the data now handles LoW units. The army will unfortunately need to be remade to work. It is in essence trying to pull data that it no longer has access to in those lists.

I've just tried on a new list and its working fine. But if after the next update it doesn't work for you then please raise the issue again.
It may also be a case that you need to delete the old data and redownload it, as occasionally issues can come when updating.
