### ISSUE TITLE
Solar Auxilia Companion Adjutant is missing the option for a Power Fist

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#3021]
**Describe the bug**
The Solar Auxilia Companion Adjutant is missing the option for a power fist. 

**To Reproduce**
1. Select a unit of SA Companions
2. Upgrade a Companion to be an Adjutant
3. Scroll through the upgrade options

**Expected behavior**
Adjutant should be able to select a power fist.

**Device and data (please complete the following information):**
- OS: Android
- App being used to create lists: Battlescribe
- App version: v2.03.27
- Data release version v17.4.2

**Additional context**
Also the option for Blast Pistols and CCWs could be unified into one option which then lets you select between Power Weapons, Charnabal Weapons, and Power Fists.

**Comment by The4D6** [comment]
This has been fixed in #3020, and the ability for companions in a companion section (not in a tactical command section) to take laspistols and chainswords has been re-added

You can find the power fist under the "Pistols and Combat weapon (Sub-menu)" option on a Companion that has been upgraded to be an Adjutant

Will be live with next release

**Comment by The4D6** [comment]
Released in 17.4.3
