### ISSUE TITLE
Backward Compatability: Publications

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3040]
There are a lot of errors raised when opening the GST in the original BS editor. A lot of publications seem to have lost thier references.

This isn't a breaking change, but needs fixing.

**Comment by Mayegelt** [comment]
Looks like on a Cursory Glance that the Age of Darkness rulebook publication has been deleted ID e77a-823a-da94-16b9
Also looks like a new publication for the Legacies of The Age of Darkness - Legions Astartes v1.2 is a new entry with a new ID, instead of just renaming it to update. So it is now 5063-981b-4ddd-e8f7 and was d0df-7166-5cd3-89fd.

Easy fix should just be readd the rulebook and then update the ID for the other file. Then whenever new ones come out then just change the name to the latest version. Of course if the update adds additional units to the pages or something then this might require the page references to also be updated.

**Comment by The4D6** [comment]
Released in v18.0.1
