### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Ultramarines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3041]
**File:** 2022 - LA - Ultramarines.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** The locutarus points is not 190 is 150 the leader is not 90 points is 150 and every unit of legacy must be upgrade with the new faq (change the profile of the weapon of the fulmentarus......and other stuff)

**Comment by The4D6** [comment]
Hi there,

New data files were published including the FAQ updates yesterday, have you downloaded the new files?

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/e6aca0a3-fa9a-4a3a-a284-6bbf3855fc75)
 
 According to the latest FAQ Locutarus are 190pts. The reason the sergeant "costs" 90 is because the Locutarus are 25pts each and you get 4 + the sarge as default. Making the sergeant cost 90pts is just a formality to make the cost correct.

Please update your data files, and if there is a genuine issue, please raise an issue and we will fix it.
