### ISSUE TITLE
Imperial Fist Tartaros Command squad unable to select Vigil Storm Shield

### ISSUE THREAD

**Issue by kd7svh** [BSData/horus-heresy#3153]
**Describe the bug**
Imperial Fist Tartaros Comand Squad is missing the option to replace it's ranged weapon with a Vigil Storm Shield.

1. New Recruit -> Horus Heresy (2022) -> Imperial Fists
2. Add Tartaros Praetor.  This model can correctly select a Vigil Storm Shield ("Legion Specific Upgrade")
3. Under "Retinue" option, select "Command Squad, Tartaros"
4. Note that there is no option for Vigil Storm Shields.  This should be in the "Terminator Ranged Weapon" section as it replaces their combi-bolter (unlike with the Praetor)

**Expected behavior**
In the "Terminator Ranged Weapon" section there should be the option to replace the combi-bolter with a Vigil Storm Shield.

**Device and data (please complete the following information):**
 - OS: MacOS
 - App being used to create lists: New Recruit
 - App version: v242
 - Data release version: Can't see an overall version but the Imperial Fists list states "rev 32"

**Additional context**
This all happened due to bug "Imperial Fists HQs Cannot Swap Guns for Shields #3069"

Where user The4D6 stated:
"I may be wrong here, so feel free to correct me if I am.
Both kinds of Imperial Fists terminator praetors have the option to exchange a combi-bolter for a vigil storm shield for 10pts.
They should not have this option."

He is wrong.  Very wrong.  Liber Astartes pg 228 clearly states that Imperial Fist Tartaros and Cataphractii units and command squads can replace their combi-bolter with a Vigil Storm Shield.  +15 points for Tartaros squads and +10 for Cataphractii.

Not to be a jerk, but it's really annoying that this got broken because some random files a bug stating what he THINKS is a problem and does zero actual investigation.  This is made worse by the fact you guys just took his word for it.  Hot tip, if a bug report starts with "I may be wrong" just assume they are.  Particularly if they aren't going to back their nonsense up with references.

**Comment by Mayegelt** [comment]
Hi ya.
The issue has actually emerged due to something else being changed by the looks of it.
If you notice if you takeba command squad of termy with a regular praetor (not Cata or Tart) the option to replace the ranged weapon works fine.
However it seems when you select a Cata or Tart Praetor with the Cata or Tart Command squad the issue seems to happen.

It will be fixed again. Unfortunately this has happened a couple of times in exactly the same scenario of X + Y not allowing Z.
Previously it was down to where the "character" catagory was placed. But I don't know if that changed.

**Comment by Mayegelt** [comment]
Doing a small dig it looks like it is an "ancestor of" issue.
4d6 coded the Termy ranged weapon SGSE to not include the Vigil shield if the ancestor of it was either type of termy praetor. This of course fixed the problem of it was offering Termy praetors an option of taking a vigil shield instead of their ranged weapon. However because a command squad comes under the praetor that selects them as an ancestor, this then broken the logic for the command squad themselves (Which is sometimes why I dislike the use of SGSEs over replication of them in some niche circumstances.).

Unfortunately I assume this was not checked in testing before it was released. Or may have been tested on a program other than BS (as I know some issues have occurred this way as well).

**Comment by Mayegelt** [comment]
As suspected, it was an "Ancestor of" issue. I have put up a pull request that should resolve this (if it goes through).

**Comment by kd7svh** [comment]
Thanks guys.
