### ISSUE TITLE
Hammer of Olympia and Head of the Gorgon: missing zero-cost Vehicle Upgrades

### ISSUE THREAD

**Issue by benjaminstraw** [BSData/horus-heresy#325]
the iron warriors right of war does not work correctly. extra armour is mentioned to become free and your are also in titled to an extra heavy slot on the force organisation

**Comment by capitaladot** [comment]
I agree that the extra armor thing should be fixed (similar issue exists in Head of the Gorgon).
The extra heavy slot probably can't be implemented in BattleScribe... maybe in version 2.0? That said, perhaps we could add it under a single-choice entry in "no category" as a bulk copy of the HS choices?

**Comment by benjaminstraw** [comment]
the single choice entry seems a  good idea but to be honest what's easiest for yourself to write program wise

**Comment by Millicant** [comment]
It will be fixed in 2.0 (the extra heavy slot).  Frankly I detest the idea of no category entries, but happily that is possible in 2.0.  

As far as Blessed Autosimulacra and Extra Armour, that's a hard one to implement.  It may be possible in 2.0 but frankly, it may be one of those things that simply has to be remembered by the player.

**Comment by capitaladot** [comment]
Auto take isn't plausible, I agree... but 0 cost sure is.

**Comment by benjaminstraw** [comment]
plenty of other things work on 0 points so that would be a Sound solution for the extra armour
