### ISSUE TITLE
Age of Darkness Army List

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#327]
Haven't even yet seen rumors of changes, yet... hopefully few, just points and a few adjusted special rules?

**Comment by thebiggeordiegeek** [comment]
I will have the ebook on day of release so can make a list of all changes

**Comment by Millicant** [comment]
Sounds good, a list will be great.  As always, all changes will have to be implemented once we have a book in hand.  

The catch will be implementing the updates here AND in the 2.0 version.

**Comment by thebiggeordiegeek** [comment]
Summery of Changes

HQ choices  
* Moritat chain fire rules updated to include the overheat rules from the jan 2016 FAQ, also chain fire is now locked to a maximum of 12 hits in total regardless of weapon.  

* Legion command squad base cost is -25pts, additional 	LCS members are -5pts 

* Chaplains cause fear 

* Primius Medicae is +10pts, can't take power fist, chainfist, boarding shield or paired lightning claws. 
Elites choices  

* Veteran Tactical Squads -25ps to base cost, additional marines are -3pts each, VTS has additional weapons from FAQ added, Veterans can now all take Combi-Weapons for +10 points
    * New Veteran Tactics
    * Resolve, Stubborn
    * Weaponmasters, +1 Weapon Skill
    * Machine Killers, +1 on armour penetration rolls
    * Marksmen, Outflank AND Sniper
    * Xenobane, re-roll To Wound against Monstrous & Gargantuan Creatures.

* Terminator Squads lose all their dedicated transport options 

* Techmarines are -10pts each base 
* Servo-Automata has heavy bolter, multi-melta, and missile launcher added to their 	wargear options 

* Apothecarion Detachment has list of units removed, may join any unit will ‘legiones astartes’ rule that isn’t in terminator armour or 	have the daemon rule. 
* Apothecarion Detahment can purhcase jump packs and SM bikes, allowing them to 	join like equipped units. Note: only regular bikes not jetbikes. 

* Dreadnoughts all have +1 attack (to base 3) as per FAQ 

* Volkite 	culverins in Contemtpor Dreads replaced with the twin-linked version 

* Legion Rapier Squads Quad Mortars only have frag rounds to start with. May purchase 	additional rounds as in book 6, including phosphex

Troops

* Legion Tactical Squads are -25pts base 

* Legion Assault Squads are -75pts base, additional assault marines are -2pts each

* Breacher squad -25pts base, additional breacher marines are +5pts each 

* Tactical Support Squad can take additonal close combat weapon for 2pts, rotor cannon and volkite charger upgrades are now free upgrades 

* Reconnaissance Squad is -25pts base 

Dedicated Transports  

* Legion Dreadnought Drop Pods are +35pts 

Fast Attacks  

* Legion Seekers are -20pts base, additional marines are +5pts, scorpius ammo changed (str5 ap2 heavy one), 

* Lightning Sunfury Missiles are +10pts, Kraken Missiles are +10pts, Phosphex Bomb Cluster -10pts, Electromagnetic bomb charges are -10pts 

* Tarantula’s are +5pts each and lose forward deployment 

* Dreadclaw Drop Pods +15pts gains internal guidance rule. Dreadclaw Drop Pods listed as only carrying regular and contemptor dreads, not leviathan or dreadeo types 

* Land Speeders are -10pts each, hunter killer missiles are -5pts each now 

* Javelins are -20pts each, gain strafing run USR, units attacking a javelin in combat suffer a -2 to hit while it isn’t immobilised due to Grav Backwash rule

Heavy Support

* Jetbike Sky Slayer Support Squadron - new jetbike unit, just regular jetbikers with multi-melta as basic, base squad is +30pts over normal jetbike squad, may only go to 5 men in total, additional men are +15pts over normal jetbikers, may upgrade to volkite or plasma for cost, all of the squad must be the same, may take sergeant upgrade 

* Deathstorm Drop Pod has automated weapons rule, basically old rule of 	automatically shooting all units within range (enemy or friend) when it arrives. 

* Plasma Executioner turret on Predators up 20pts 

* Predator Strike Armour Squadron, Executioner plasma destroyer is +20 points on old price. heavy conversion beamer is -5 points. If you take 3, one of them can be a Squadron Command Tank for +35 points, if unit is in coherency, all ignore Crew Shaken on a 4+, if they all shoot at a single target within 24", they gain Tank Hunter and Monster Hunter.

* LR Phobos is 	-25pts 

* LR Proteus is 	-20pts, can take a hull-mounted twin-linked lascannon

* If you take 3 LR, one of them can be a Squadron Command Tank for +35 points.

* Land Raider Achilles can take thudd gun ammos same as rapiers, at same price 

* LR Achillies-Alpha can also take additonal ammo types 

* Vindicators are now squadrons as in book 6. with additional rules from FAQ ,  if you take 3, one of them can be a Squadron Command Tank for +35 points.

* Legion Artillery Tank Squadron, still 0-1 if you take 3, one of them can be a Squadron Command Tank for +35 points

* Spartan is 	+10pts, laser destoryers are free upgrades, flare shield is +20pts over old price 

* Sicaran Venator may take second pintle-mounted weapon (full list) 

* Sicaran is +30pts and can take a pintle mounted weapon 

* Kharybdis is -25pts 

* Deredeo dreadnought has third arm option, heavy lascannon option str10, ap2 heavy 2, exoshock, exoshock 	means if a hit scores a penetrating hit, then on a 4+ a second automatic pen is caused ignoring cover 

* Whirlwind Scopius can take pintle-mounted weapons 

* Malcador is now heavy support  with -25pts base cost, battlespeed now allows it to fire its main weapon (top turret) at full BS skill before or after moving flat out. Malcador is 1-3 in squadrons, Malcador receives wider wargear selection covering basic stuff like pintle-mounted weapons 

Lords of War  

* Typhon is +45pts base 
* Falchion is +25pts, can take a neutron wave capacitor which adds the ‘feed back’ and 	‘shock pulse’ special rules to it’s volcano cannon. 

* Single knights can now be taken 

Rites of War  

* Orbitial Assault: dreadnought and contemptor talons can take dreadclaws or 	dreadnought droppods even in talons of 2 or 3. rapier batteries can 	take drop pods. 
* POTL: 	majority of units in the list must have the legiones astartes rule, 	so more infantry than vehicles. 
* Armoured 	breakthrough: the command tank option gains the ‘master of the 	legion rule’

**Comment by Millicant** [comment]
I'm going to start work on this over the weekend.  Normally I insist on
waiting to have the book in-hand, but these are big changes and people
(myself included) are excited about them.  Better to implement now and
adjust if there are errors once I have the books.

To incentivize some alpha testers - I may implement and release the updates
to the 2.0a catalogues first, if only by a couple days.

On Fri, Jul 15, 2016 at 8:49 AM, thebiggeordiegeek <notifications@github.com

**Comment by capitaladot** [comment]
That's Garro's changelist from the Heresy30k forum. http://heresy30k.invisionzone.com/index.php?/topic/7475-legion-age-of-darkness-legion-army-list-changes/

How can we pitch in? Should the new book be the cutover point to the v2 project, or is @Jonskichov too far out from releasing BS2?

**Comment by Millicant** [comment]
Tell you what.  Let's make this easy on ourselves.  

We are too far from 2.0 to make this a changeover point.  Why don't you implement the updates in the regular and I'll keep working on 2.0?  That way we can avoid double work for either of us and still make forward progress.  Sound good?

**Comment by thebiggeordiegeek** [comment]
That's right I used Garros list as the basis of the list because he had already done the job and didn't see any point doing it all again, but I double checked it all.

**Comment by Millicant** [comment]
@thebiggeordiegeek yes but credit where it's due is important. 

@capitaldot let me know what you think! I'd like to push out this update this weekend if possible. If you don't want to split it up, it's all good, I'll get started. Just don't want to end up with more merge conflicts. :)

**Comment by Millicant** [comment]
Okay I have the digital version now.  I'm going to go over the 2.0a now with the details and make sure I get it all correct.  

Once I'm done, I'll upload the changes and then @capitaladot I'm going to start on the 1.15 catalogues (here) unless you tell me otherwise.  Probably be tomorrow or the day after.

**Comment by Mayegelt** [comment]
https://drive.google.com/open?id=0B2WSzVPkudYKWFBmek9IV0lBZUU

That is my 1.15 update. I didn't increase the version number with this update as I kinda just hashed it together. I think I got all the main updates in there. I didn't however amend any of the Rites of War and couldn't see anywhere where it said about being allowed a single knight.

**Comment by capitaladot** [comment]
@Millicant Sorry, had our biweekly 30k club meeting this weekend, so got to look at the book (and a digital copy), but haven't gotten to work yet.
I'll get started this week.

**Comment by capitaladot** [comment]
This is mostly done and released, now; going back through and hitting the things that I missed.
