### ISSUE TITLE
Blackshields ZM

### ISSUE THREAD

**Issue by MUKIMUKII** [BSData/horus-heresy#3310]
When I try to make a list for BG- blackshields in a zone mortalis force , I cannot select the oaths of vengeance, they don't appear as an option.
This is on new recruit.

**Comment by The4D6** [comment]
![image](https://github.com/user-attachments/assets/d2bb6446-51b6-4270-8c3a-61aad6e7cc66)
![image](https://github.com/user-attachments/assets/7cf6a844-e178-45e9-80a6-db0ad2cfa104)
I'm not convinced this is an issue, can you provide further explanation?

**Comment by Mayegelt** [comment]
@The4D6 I think I solved this one before the last release, but it might be that it didn't get closed or soemthing. Or the person was loading up an old roster before it was working, and as such couldn't see the option to fix it, rather than making a new one.
I'm happy for this one to be closed as I'm getting the same as you of it working fine.
