### ISSUE TITLE
[Anon] LA -  XVI: Sons of Horus: Error received when trying to add 6x Cataphractii (bulky 2) to a dreadclaw drop pod.  

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3354]
**Problem:**
Error received when trying to add 6x Cataphractii (bulky 2) to a dreadclaw drop pod.  

**Expected:**
Dreadclaw has a transport capacity of 12 so I expected 6x (bulky 2) would be ok to transport.

 **Additional Info:**
Terminator Cataphractii Squad: Dreadclaw Drop Pod cannot be selected while hidden

**List:** https://www.newrecruit.eu/app/list/Rcu4D

**Comment by Mayegelt** [comment]
Even though it had the capacity to, it can't use all the seats for regular dudes. Clearly 1-2 seats are VIP seats and the extra person refuses to pay the extra £££ to have 2 arm rests of their own, rather than 2 shared ones with basic cup/popcorn holders

"A Legion Terminator Cataphractii squad numbering no more than five models may take a Legion Land Raider Proteus Carrier or Legion Dreadclaw Drop Pod as a Dedicated Transport."
