### ISSUE TITLE
Add support for Legio Custodes in AoD

### ISSUE THREAD

**Issue by DonMorr** [BSData/horus-heresy#541]
It would be great if the "Legio Custodes" could be added to the AoD data file.
They need to be added as a possible Allied Detachment, with one unit filling the compulsory HQ choice rather than its usual role.

The following units are currently available:
- Legio Custodes Caladius Grav-Tank
- Custodian Guard Squad
- Sentinel Guard Squad

**Comment by thebiggeordiegeek** [comment]
There are no rules yet widely available for the Grav Tank, just a sheet seen at the open day (I was there and I bought one, didn't come with rules).

So currently there is no way to actually select it for your army. I suspect that will change once it's available for sale, until then the only units that the team could add would be the two Custodes Squads.

Would be awesome if they could be added, but given the other issues, I suspect this one may have to wait a little while.

**Comment by DonMorr** [comment]
I also got my hands on a Grav Tank and the experimental rules sheet (played a game with it last week and it did very well!). Anyway, in November's White Dwarf, it stated that the Custodian & Sentinel Guard could be used as an allied attachment, but I don't think it mentioned the grav tank - you could infer that all existing "Legio Custodes" could be used as a possible Allied Detachment.

I've already added the war gear and weapons for the 3 custodian units into a branch on my fork of the repo, so am happy to continue with adding the units. The experimental rules for the grav tank can easily be updated to the final rules whenever they come out.
The main thing I would need direction on in this task how/where to add the "Legio Custodes" force to the data file. Would I simply treat them as another legion, or do they needed to be handled differently.

**Comment by thebiggeordiegeek** [comment]
I am not so much a programming guy these days, but I would suggest that perhaps they would be better as a force of their own, in the same way that the Solar Auxilia are.

**Comment by thebiggeordiegeek** [comment]
And if you have the rules for the tank then awesome, I would say add away.

Wish they gave me a copy of the rules!

**Comment by DonMorr** [comment]
If you'd like me to send you a photocopy, please let me know.

**Comment by Millicant** [comment]
We are going to have to wait on the Custodes.  They have not officially been added to the system yet.  My policy on new additions is that they must be published somehow with an appropriate way to add them to the existing framework.  For instance - the new Dreadnoughts that received rules at Forgeworld.co.uk along with where they fit into the current lists.

Sorry to be a downer, but I dislike adding speculative/unofficial items to the catalogues.

**Comment by thebiggeordiegeek** [comment]
If I could be so bold, but the rules for these were published in White Dwarf so they are official.

I guess it depends on the policy for stuff added to the army lists via White Dwarf.

**Comment by capitaladot** [comment]
These were published in White Dwarf, weren't they?

**Comment by Millicant** [comment]
Hmmm @thebiggeordiegeek you may be correct.  I knew there were stats/rules but there is that one line about "select one unit to fill the Compulsory HQ rather than it's usual role."  That makes this rather sticky since it will be a new catalogue but with almost nothing in it.  Oh well - it will still make it usable for people.  

As far as the Grav tank - that will have to wait.  I'm confident it will have rules uploaded once it's available on Forgeworld - then we can add it.  

I will write the foundation for this new catalogue this weekend - once uploaded we can edit/add as needed.

As a follow-up: Is there anything I'm missing in this White Dwarf?  There's just the three pages, right?  Overall rules/wargear, and two units.

**Comment by thebiggeordiegeek** [comment]
No just those three pages.

The Custodes will form part of the Talons of the Emperor army list as per this months White Dwarf, which will also include Sisters of Silence, but we really don't have any rules for them.

They were originally going to be rules for the Sisters in this months White Dwarf, but they haven't been included because they thought Inferno would be released by now!

**Comment by zopha** [comment]
Grav tank rules have been posted today by FW on the grav tank product page on their store.

**Comment by Millicant** [comment]
Okay so I've made the Catalogue for an Allied detachment.  Seems to work so far.

Only catch is the bit in the Custodes PDF about the grav-tank.  Apparently it can be taken in any detachment on a one-per basis after a corresponding infantry unit, but with exceptions of course.  That is going to be a MAJOR pain in the ass.  I'll work on it, but at least the Allied detachment will be in place and accessible at the moment.

**Comment by zopha** [comment]
Inferno has superseded these rules.
