### ISSUE TITLE
Ammo for quad mortar 

### ISSUE THREAD

**Issue by bryankia** [BSData/horus-heresy#551]
Hey I can't add a rite of war.... just kidding :)

I can upgrade to a quad mortar / thud fun but don't see an option for shatter shells or the others. 

Thanks to the team that makes this happen.

**Comment by thebiggeordiegeek** [comment]
Hey dude

You can upgrade the Rapier to a thud gun, however for some reason, I am guessing because it's a separate entry in book 6, the Thud Gun is better represented by the Legion Quad Launcher Support Battery where the additional shell types can be selected.

Would be handy if they were reintegrated, but if that's not possible then that's cool, we will cope.

**Comment by bryankia** [comment]
Sometimes reading is hard. Sorry I missed that. 

Thanks

**Comment by thebiggeordiegeek** [comment]
Easy enough to miss, the change happened not long after book 6 came out and in that they were indeed a separate entry.

I imagined they would be in the new Red Book, but alas they were not.

Hope I have cleared that up for you pal.
