### ISSUE TITLE
Legion Jetbikes Sky-Slayer Squadron:

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#602]
Please add Legion Jetbikes Sky-Slayer Squadron: to support

**Comment by zopha** [comment]
Thanks for submitting the issue!

This issue is covered in #568

We're working towards getting the files updated to the LA Army List red book at the moment and I'm working on the Heavy support section. Just waiting for two existing pull requests to be QA'd and cleared for pintle-mount weapons and some of the standard vehicle wargear. If you have some time and are willing to do QA and provide any feedback on my changes I'd be greatful, just let me know! Desktop BS is preferred as it's easier to change the datafiles.

Once those are cleared I'll be adding the Sky Slayer squadron, the Malcador tank and then a finishing update for the rest of the Heavy Support units.

----
Since this is a duplicate and currently being worked on I'll close this off.
