### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by TomTheHand** [BSData/horus-heresy#612]
Hey all! I'd like to help out with 30k data file development. I've been making changes to data files on my own, and I feel like I've got the hang of it, so I'd like to see if I can help the project.

**Comment by zopha** [comment]
Hi @TomTheHand 

Are you interested in working on any particular armies? Do you have any experience using git? Might be an idea to create a fork of the dataset and make some changes to get the hang of git if not.

Due to the XML structure of the datafiles it can be impossible to get them to merge with other changes. Unless you're a hardcore programmer with XML skills and plenty of time, you can try to manually resolve them, otherwise, it's unmanageable :< so we probably have to coordinate changes so we don't mess things up for each other.

Since I'm new here myself I won't be sending an invite, I'll leave that up to the others ( @millicant and @capitaladot ) but go to https://gitter.im/BSData/horus-heresy , a chat channel for this repo, it's quiet there at the moment but it can be good to talk about what needs to be done. https://gitter.im/BSData/wh40k is the more active one for 40k :)

**Comment by zopha** [comment]
Hi @TomTheHand Have you had the time to look into Git or getting on to the chat channel on gitter.im?

**Comment by zopha** [comment]
No response so I'll close this off. We can reopen again if there's a response.

**Comment by capitaladot** [comment]
I still have no internet at home and was not able to review this.

**Comment by zopha** [comment]
Apologies, I was referring to the OP @TomTheHand 

I'll reopen it for review.

**Comment by capitaladot** [comment]
+1

**Comment by amis92** [comment]
@alphalas @capitaladot I'm not sure what should I do, capitaladot '+1'd it, alphalas closed this now, Tom gave no answer.

Leave it, invite him, or...?

**Comment by alphalas** [comment]
I just closed it because it was open for so damn long with no response

**Comment by zopha** [comment]
We don't have many files to work on and they've got a good bit of stuff in each of them, we really need good communication otherwise we could start running into merge conflicts.

It's been open for nearly 2 months with no response from @TomTheHand so I'd say close it and if Tom responds or engages us on gitter ( https://gitter.im/BSData/horus-heresy ) we can reopen it again.
