### ISSUE TITLE
Loyal death guard terminator comand squad missing heavy flamer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#633]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.12

**Platform:** Android

**Dropbox:** No

**Description:** Loyal death guard terminator comand squad doses not have the choice of heavy flamer

**Comment by zopha** [comment]
I had a look and the option is there

![2017-01-04 12_58_39-roster editor v2 00 09 - new roster warhammer 30 000 - the horus heresy v43](https://cloud.githubusercontent.com/assets/1666415/21642967/9dc417e4-d27d-11e6-8600-548688053034.png)

In the bottom right of the screenshot. Unless it's something else?

Deathshroud have hand-flamers, the overview doesn't show it yet but that will be fixed in a future update.

**Comment by zopha** [comment]
@MrRta1910 isn't that one in the screenshot the normal terminator command squad? The heavy flamer is present if it's changed to Cataphractii armour.

I had a look at the Delagatus and a few of the Primarchs and they have the same options. If it's a command squad for a particular character let me know the name and I can check it.

**Comment by MrRta1910** [comment]
Here is what I see
![screenshot_2017-01-05-07-15-49](https://cloud.githubusercontent.com/assets/7269431/21657567/ff26632c-d316-11e6-9bf2-ad1a785aa34f.png)
![screenshot_2017-01-05-07-15-43](https://cloud.githubusercontent.com/assets/7269431/21657568/ff27e8c8-d316-11e6-9156-c4d90f5d5ad7.png)
![screenshot_2017-01-05-07-15-39](https://cloud.githubusercontent.com/assets/7269431/21657569/ff2a8650-d316-11e6-8d8a-86476541c62a.png)

**Comment by capitaladot** [comment]
You have the wrong command squad.

**Comment by MrRta1910** [comment]
What squad is wrong
![screenshot_2017-01-05-07-45-43](https://cloud.githubusercontent.com/assets/7269431/21658533/25f22dde-d31b-11e6-9b2c-4ad18396fc6b.png)
![screenshot_2017-01-05-07-45-41](https://cloud.githubusercontent.com/assets/7269431/21658532/25ea7f62-d31b-11e6-9bc8-272a711070a3.png)
![Uploading Screenshot_2017-01-05-07-45-32.png…]()

**Comment by capitaladot** [comment]
You selected the wrong command squad version. There are different versions
based on armor.

**Comment by zopha** [comment]
@MrRta1910 Thanks for the screenshots! Makes things easier to find but that's the standard Command Squad (equiped with power armour), not the terminator one. The standard one doesn't get access to any flamer weapons, they shouldn't have the chem munitions additional option at all (so that will have to be removed) and I don't think there's a rite of war that swaps something for a flamer for them.

What HQ unit are you attaching them to? The HQ unit they're attached must have Terminator armour selected, the standard Power armour command squad is then replaced with the Terminator armour version which will have access to a Heavy Flamer.

**Comment by MrRta1910** [comment]
Cataphracti  armored prator I have a Dropbox link if u want for the army list

**Comment by zopha** [comment]
I've a feeling it's a corruption in one of three things. Either the data
files, that specific list or possibly an issue with battlescribe in your
device.

Can you try deleting and refreshed your data files and then try again? Just
go in to manage data and in the menu there choose delete all data. I
recommend you save a copy of any rosters you don't want to lose before
doing this. It won't remove them but it's always good to have a back up.

If that doesn't fix it can you add another unit that can take a terminator
command squad. A delegates in terminator armour should work. If that works
try removing the praetor and adding it back in again.

If that doesn't work can you create a new list and test with basic units
and a praetor in terminator armour? If that works then the original list
may have something corrupt in it :(

Army list files are usually quite small so you should be able to attach the
file directly to a reply on the github webpage, just drag it in to the text
box and it'll upload.



On 4 Jan 2017 21:24, "MrRta1910" <notifications@github.com> wrote:

Cataphracti armored prator I have a Dropbox link if u want for the army list

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/issues/633#issuecomment-270490791>,
or mute the thread

**Comment by zopha** [comment]
Okay, so if you go with a different force your Preator has the option for a terminator command squad?

Do you have dropbox linked? Perhaps remove it, delete your data and refresh it again. I can't think of much else that would cause this, the only condition on it I can see it to hide it is if Blackshields is selected but removes the legion selection as well and command squads in general.

Other than that I'm not sure what's causing this issue for you, the next release that updates the Legion catalogue might force the update and fix it.

**Comment by zopha** [comment]
@MrRta1910 I've changed the ID on the terminator command squad so it should see it as a new selection and it's in today's release so you should have it in a few hours. 

If the command squad doesn't appear after the update can you clear out your catalogue files and try again? Instructions for clearing data are available here: https://battlescribe.net/?faq=refreshData
