### ISSUE TITLE
Moritat missing second pistol options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#634]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** No

**Description:** Just a couple things. Thd Night Lords Horror Cult Rite of War is missing from selection. And the Moritat selection does not allow for the selection of a close combat weapon on top of the two pistol selections.

**Comment by zopha** [comment]
I see what you mean.

Should have selections for 
Bolt Pistol 1
Bolt Pistol 2
Combat Blade 1

While it only has the options for 

Bolt Pistol 1
Combat Blade 1

Looking at the entry I can see the Moritat has too many options as well, some of them are not allowed. That will be fixed in the next release. We can look at Bolt Pistol 2 options in the release after that.

The Horror Cult Rite of War will be dealt with later, rites usually complicate things so it could need a good bit of work to implement.
