### ISSUE TITLE
Problems loading data file

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#636]
Update of battlescribe seemed to break the loading of data files on iOS

Bs v2.00.13
Heresy data file v42

Screen shot of error below. I specifically noticed sponsons for predator tanks missing (all) and main cannon options missing.

I will check on macOS shortly.

![img_0532](https://cloud.githubusercontent.com/assets/13860904/21601133/0718e716-d14c-11e6-82b5-9c286c6e83e8.PNG)

**Comment by zopha** [comment]
Thanks @cowomo404 It's a conflict with the old files and the updated ones because of the changes needed to update to battlescribe 2 entries. Unfortunately this may happen again as not everything has been updated to the new standard. I'll do some research and see if there's any other way to avoid this in the future.

Can you clear out your catalogue data please, I had the exact same issue on my tablet and deleting the old catalogue files fixed it for me. You can delete data from the menu in Manage Data. Take a look at this: https://battlescribe.net/?faq=refreshData

**Comment by cowomo404** [comment]
Thanks @zopha that seems to do the trick to get the data file to load, so now it's just a data issue.  Seems odd thought as I thought I had seen a previous issue with not all that f the predator turrets being available. And that seems to be the case again (maybe that was a v1 issue and those changes were never back filled to v2?). I'll capture a separate issue item for that to track.

![img_0533](https://cloud.githubusercontent.com/assets/13860904/21601443/70b081f8-d150-11e6-86a9-11756e88b933.PNG)

**Comment by cowomo404** [comment]
Update confirmed it was a documented issue that was fixed in v1. Issue item #345

**Comment by zopha** [comment]
Some research and 

> BattleScribe uses the revision no. to determine whether it needs to download an updated file.

So I made a mistake by not incrementing the GST file. This will be fixed in the next release.
