### ISSUE TITLE
Ultramarines RoW - The Logos Lectora

### ISSUE THREAD

**Issue by darkestvisions** [BSData/horus-heresy#651]
Receiving an error warning with the following;

Legiones Astartes: Age of Darkness Army List v205 (The Age of Darkness) must have 1 more selections from HQ (minimum 4).

As far as I can tell, an Age of Darkness list is only required to have 1 HQ choice, and using The Logos Lectura requires an additional compulsory HQ (in the form of Master of Signal or Damocles Command Rhino - which I have included) - so a requirement of 2 HQs, not 4 HQs.

**Comment by zopha** [comment]
There's a few things happening here and are conflicting with each other.

HQ is Min 1 by default. 
It gets incremented when the Logos rite is selected so up to 2.
It gets incremented by the Master of Signal as that entry is a support consul in other armies so up to 3 now.


Max is 3 by default.
It get incremented by 3 for Age of Darkness

Rather than setting the min HQ to 2, as a damocles and MoS aren't standard compulsory HQ units, we can increase the max by 1. The compulsory requirement in the Damocles and MoS entries are already set so this change will solve this issue.

We'll also have the issue that Ultramarines can take a Damocles as a dedicated tranport for a MoS... so that will require more work at a later stage. It's going to take a few more steps to get working as it looks like you could take two Damocles in a Logos Lectora list.
