### ISSUE TITLE
Solar Auxilia - Household Retinue missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#668]
**File:** (HH) Solar Auxilia - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Auxilia Household Retinue missing
When you take a Lord Marshall or Lord Ireton MeSade as HQ, Veletaris Storm Sections may be taken as Household Retinue Squads in addition to their usual role. Such Squads are WS4 but do not have the Hold The Line special rule. In addition, they have Preferred Enemy (Infantry) special rule while the Lord Marshall is present on the table and not falling back. Household Retinue Squads are Elites choices (and not Tercio Troops choices) for the army, and may take either a Dracosan Armoured Transport or an Auxilia Arvis Lighter as a Dedicated Transport choice.

**Comment by Steelmaelstorm** [comment]
Page 24, "Horus Heresy Imperialis Army Lists" redbook

Also

HH4: Conquest p256

**Comment by zopha** [comment]
I've added in the selection for the Lord Marshel. It's the same entry the Legate has and will be available in the next release. If they're missing any weapon options let us know and they'll be updated. I'd go through and update the entry but I'm just short on time this week.

Thanks for the Solar Aux submission! We're doing a legion army review first but if there's any other issues with Solar Aux please submit an issue and we'll try to get it fixed fairly quickly otherwise it'll be done when we get to the Solar Aux army review.
