### ISSUE TITLE
Mechanicum Taghmata v39 Avenger and Knight Porphyrion

### ISSUE THREAD

**Issue by ThomasBroom** [BSData/horus-heresy#771]
Putting together an army in Matrix of Ruin (tyvm for that last update!) and am getting an error saying that only one Avenger Strike Fighter may be taken. Also, with the points now confirmed as the same as the experimental rules, are you planning to add the Acastus Knight Porphyrion to the roster?

Thanks again and keep up the good work!

**Comment by zopha** [comment]
Yeap! Just been working on getting issues fixed in the legion file before creating more with Lord of War changes :) We need to make some changes to knights so they're available as Lord of War units for other armies so the Porphyrion will be added for mechanicum at the same time.

Looks like the Crusade Fleet units has a max 1 constraint applied to them. I'll have a better look but if nothing requires it I'll remove that constraint.

**Comment by zopha** [comment]
Porphyrion will be in the next release, which may be awhile as the Legion catalogue needs to be beaten into shape. The files are available on the master branch though https://github.com/BSData/horus-heresy/archive/master.zip

Swapping out the files on desktop is fairly straight forward, if you want to try it on Android there are a few more steps and I can provide them if you'd like to try them. I've no idea about setting them up on iphone :(

I'll have a look at the Avenger soon if I haven't fixed it already.

**Comment by alphalas** [comment]
Basically only way to make it work on iOS is to have Dropbox- you do the change on a pc, then sync your idevice to Dropbox

**Comment by capitaladot** [comment]
@zopha Porphy is wrong in the Questoris list; should be a Lord of War, not a choice at for Questoris Ranks.

**Comment by capitaladot** [comment]
@zopha Castellax and Vorax are also incorrectly shown without the choice of Archmagos D.

**Comment by zopha** [comment]
There are issues hiding linked entries from the GST. They have to be hidden before a hidden modifer with a constraint will work on them. At least that's what Alphalas had found when setting up AoDC. I did a quick test and it was the same, they didn't hide :( I should have logged an issue for it since I didn't fix it in the commit.

As for the household ranks, it can be taken as any except for Scion Aspirant or Scion Uhlan. I forgot about the last two, I had it setup on the Questoris catalogue but didn't think to check it for the GST files.
![2017-03-08 18_04_43-the-horus-heresy-book-7-inferno-large- pdf - adobe acrobat reader dc](https://cloud.githubusercontent.com/assets/1666415/23716906/c21e39ca-0429-11e7-98ea-d663cbdd753c.png)

**Comment by capitaladot** [comment]
Oh, shit... There was a change in b7 from experimental rules. My mistake!
