### ISSUE TITLE
Legion-specific terminator options are showing for all legions.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#857]
Teleportation (only for Imperial Fists and Night Lords)
Ilastus Assault Cannons (only for Imperial Fists and Blood Angels)

**Comment by zopha** [comment]
Have you been able to compare the released files with the master branch to see if this has been fixed or if it's new Battlescribe bug?

**Comment by capitaladot** [comment]
No... which git revision might have fixed this?

**Comment by zopha** [comment]
I can't find it now :( It may have been a fix that was done awhile ago and has since changed. I definitely remember doing something on it but that could have been a month or a year previously or it may have been part of a fix that was wiped.

I'll have a look at it if I can get some battlescribe time today and see what's happening/implement a fix for it.

**Comment by zopha** [comment]
The cannon was not hidden so was on display for all.
The terminators should have had Teleport Transponder instead of Teleport Assualt.

Both fixed in the Astartes branch and will be resolved when it's merged.
