### ISSUE TITLE
Thousand sons Book 7 Progress thread. 

### ISSUE THREAD

**Issue by meatlaser** [BSData/horus-heresy#881]
Hey guys,  

Not sure who to address this to but I am starting this thread so the community can keep track of what's going on with Book 7. I have some questions, firstly who is currently working on the 30k data files? Second is there a direct way to contact this person for updates. Third, is there a way the community that can't code can help? Lastly, what is the eta or the currently progress of the data files? When can we expect them? 

Thanks 

~Jason

**Comment by alphalas** [comment]
Refer to #729 for progress - as to who's in charge of it it's pretty well split between myself, @kohato, @capitolidot, and @zopha - we're all on Gitter (gitter.im or on mobile app), that's the best way to get a hold of us if you actually want to converse.

How to help; fortunately if you don't no xml but have BattleScribe on pc you can edit files, and if you ask for permission to edit here on GitHub you can help update. However, since we only have a few number of cats total, we have to try to carefully manage who's working on what when.

As to the next release, we're not sure - we can discuss further on Gitter. 

Thanks for the interest!
