### ISSUE TITLE
Sekhmet as Troops issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#966]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 

- [x] When creating a force for Thousand Sons, using the Rite of War "Guard of the Crimson King", unable to select Sekhmet Terminator Cabal as a troop. 
- [x] They are also removed from the elite choices. 
- [x] Additionally, an error appears when selecting Magnus the Red, stating that he is Max 0

**Comment by zopha** [comment]
The hide condition on the Sekhmet Troops was set to OR instead of AND. It hid the seleciton if the force had 0 selections of PofL or Guard of the Crimson King. I've added in the extra conditional that will make the troops selection show up if Magnus is in the force (Sire of the Thousand Sons)

Sekhmet elites are no long hidden. The rules seems to make you fill the compulsory troops slots with them but doesn't mention anything about removing them from elites. Does that sound right to everyone?

The Max 0 error will be fixed on the next release. You'll still see it if you take HQ Magnus but you just need to set the Rite of War to Pride of the Legion to fufil the requirements.
